// Generated by stratus_hls 19.25-s100  (93142.260418)
// Wed Sep  7 16:24:57 2022
// from fir.cc
#include "fir_LessThan_1U_10_4.h"

struct fir_LessThan_1U_10_4;
fir_LessThan_1U_10_4::fir_LessThan_1U_10_4(sc_module_name name) : sc_module(name) 
    ,in1("in1")
    ,out1("out1")
{
  SC_METHOD(fir_LessThan_1U_10_4_thread_1);
  sensitive << ( in1 );

}
void fir_LessThan_1U_10_4::fir_LessThan_1U_10_4_thread_1(){
  out1 = (/*imp*/sc_uint<1>)(in1.read() < ((/*imp*/sc_uint<3> )(7ULL)));
}
