// Generated by stratus_hls 19.25-s100  (93142.260418)
// Wed Sep  7 16:24:57 2022
// from fir.cc
#ifndef CYNTH_PART_fir_fir_Not_1U_1U_1_h
#define CYNTH_PART_fir_fir_Not_1U_1U_1_h

#include "systemc.h"
/* Include declarations of instantiated parts. */


/* Declaration of the synthesized module. */
struct fir_Not_1U_1U_1 : public sc_module {
  sc_in<sc_uint<1> > in1;
  sc_out<sc_uint<1> > out1;
  fir_Not_1U_1U_1( sc_module_name name );
  SC_HAS_PROCESS(fir_Not_1U_1U_1);
  void fir_Not_1U_1U_1_thread_1();
};

#endif
