
// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Jul 28 2022 18:25:59 CEST (Jul 28 2022 16:25:59 UTC)

// Verification Directory fv/multiplier 

module multiplier(a, b, clk, pdt);
  input [3:0] a, b;
  input clk;
  output [7:0] pdt;
  wire [3:0] a, b;
  wire clk;
  wire [7:0] pdt;
  assign pdt[0] = 1'b0;
  assign pdt[1] = 1'b0;
  assign pdt[2] = 1'b0;
  assign pdt[3] = 1'b0;
  assign pdt[4] = 1'b0;
  assign pdt[5] = 1'b0;
  assign pdt[6] = 1'b0;
  assign pdt[7] = 1'b0;
endmodule

