
// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Jul 29 2022 11:03:41 CEST (Jul 29 2022 09:03:41 UTC)

// Verification Directory fv/multiplier 

module multiplier(a, b, clk, pdt);
  input [6:0] a, b;
  input clk;
  output [13:0] pdt;
  wire [6:0] a, b;
  wire clk;
  wire [13:0] pdt;
  wire [13:0] \pdt_int[0] ;
  wire [6:0] a_int;
  wire [6:0] b_int;
  wire mul_31_25_n_0, mul_31_25_n_1, mul_31_25_n_2, mul_31_25_n_3,
       mul_31_25_n_4, mul_31_25_n_5, mul_31_25_n_6, mul_31_25_n_7;
  wire mul_31_25_n_8, mul_31_25_n_9, mul_31_25_n_10, mul_31_25_n_11,
       mul_31_25_n_12, mul_31_25_n_13, mul_31_25_n_14, mul_31_25_n_15;
  wire mul_31_25_n_17, mul_31_25_n_18, mul_31_25_n_19, mul_31_25_n_20,
       mul_31_25_n_21, mul_31_25_n_22, mul_31_25_n_23, mul_31_25_n_24;
  wire mul_31_25_n_25, mul_31_25_n_26, mul_31_25_n_27, mul_31_25_n_28,
       mul_31_25_n_29, mul_31_25_n_30, mul_31_25_n_31, mul_31_25_n_32;
  wire mul_31_25_n_33, mul_31_25_n_34, mul_31_25_n_35, mul_31_25_n_36,
       mul_31_25_n_37, mul_31_25_n_38, mul_31_25_n_39, mul_31_25_n_40;
  wire mul_31_25_n_41, mul_31_25_n_42, mul_31_25_n_43, mul_31_25_n_44,
       mul_31_25_n_45, mul_31_25_n_46, mul_31_25_n_47, mul_31_25_n_48;
  wire mul_31_25_n_49, mul_31_25_n_50, mul_31_25_n_51, mul_31_25_n_52,
       mul_31_25_n_53, mul_31_25_n_54, mul_31_25_n_55, mul_31_25_n_56;
  wire mul_31_25_n_57, mul_31_25_n_58, mul_31_25_n_59, mul_31_25_n_60,
       mul_31_25_n_61, mul_31_25_n_63, mul_31_25_n_64, mul_31_25_n_65;
  wire mul_31_25_n_66, mul_31_25_n_67, mul_31_25_n_68, mul_31_25_n_69,
       mul_31_25_n_70, mul_31_25_n_71, mul_31_25_n_72, mul_31_25_n_73;
  wire mul_31_25_n_74, mul_31_25_n_75, mul_31_25_n_76, mul_31_25_n_77,
       mul_31_25_n_78, mul_31_25_n_79, mul_31_25_n_84, mul_31_25_n_85;
  wire mul_31_25_n_86, mul_31_25_n_87, mul_31_25_n_89, mul_31_25_n_92,
       mul_31_25_n_93, mul_31_25_n_94, mul_31_25_n_95, mul_31_25_n_96;
  wire mul_31_25_n_97, mul_31_25_n_99, mul_31_25_n_131,
       mul_31_25_n_132, mul_31_25_n_134, mul_31_25_n_135,
       mul_31_25_n_137, mul_31_25_n_138;
  wire mul_31_25_n_140, mul_31_25_n_141, n_0, n_1, n_2, n_3, n_4, n_10;
  wire n_11, n_12, n_13, n_158, n_159, n_160, n_161, n_162;
  wire n_163, n_164, n_165, n_166, n_167, n_168, n_169, n_170;
  wire n_171, n_172, n_173, n_174, n_175, n_176, n_177, n_178;
  wire n_179, n_180, n_181, n_182, n_183, n_184, n_185, n_186;
  DFQD1BWP \pdt_int_reg[1][13] (.CP (clk), .D (\pdt_int[0] [13]), .Q
       (pdt[13]));
  DFQD1BWP \pdt_int_reg[1][12] (.CP (clk), .D (\pdt_int[0] [12]), .Q
       (pdt[12]));
  DFQD1BWP \pdt_int_reg[1][10] (.CP (clk), .D (\pdt_int[0] [10]), .Q
       (pdt[10]));
  DFQD1BWP \pdt_int_reg[1][6] (.CP (clk), .D (\pdt_int[0] [6]), .Q
       (pdt[6]));
  DFQD1BWP \pdt_int_reg[1][5] (.CP (clk), .D (\pdt_int[0] [5]), .Q
       (pdt[5]));
  DFQD1BWP \pdt_int_reg[1][9] (.CP (clk), .D (\pdt_int[0] [9]), .Q
       (pdt[9]));
  DFQD1BWP \pdt_int_reg[1][4] (.CP (clk), .D (\pdt_int[0] [4]), .Q
       (pdt[4]));
  DFQD1BWP \pdt_int_reg[1][3] (.CP (clk), .D (\pdt_int[0] [3]), .Q
       (pdt[3]));
  DFQD1BWP \pdt_int_reg[1][11] (.CP (clk), .D (\pdt_int[0] [11]), .Q
       (pdt[11]));
  DFQD1BWP \pdt_int_reg[1][8] (.CP (clk), .D (\pdt_int[0] [8]), .Q
       (pdt[8]));
  DFQD1BWP \pdt_int_reg[1][2] (.CP (clk), .D (\pdt_int[0] [2]), .Q
       (pdt[2]));
  DFQD1BWP \pdt_int_reg[1][1] (.CP (clk), .D (\pdt_int[0] [1]), .Q
       (pdt[1]));
  DFQD1BWP \pdt_int_reg[1][7] (.CP (clk), .D (\pdt_int[0] [7]), .Q
       (pdt[7]));
  DFQD1BWP \pdt_int_reg[1][0] (.CP (clk), .D (\pdt_int[0] [0]), .Q
       (pdt[0]));
  DFQD1BWP \pdt_int_reg[0][13] (.CP (clk), .D (n_0), .Q
       (\pdt_int[0] [13]));
  DFQD1BWP \pdt_int_reg[0][8] (.CP (clk), .D (n_161), .Q
       (\pdt_int[0] [8]));
  DFQD1BWP \pdt_int_reg[0][9] (.CP (clk), .D (n_4), .Q (\pdt_int[0]
       [9]));
  DFQD1BWP \pdt_int_reg[0][10] (.CP (clk), .D (n_3), .Q
       (\pdt_int[0] [10]));
  DFQD1BWP \pdt_int_reg[0][5] (.CP (clk), .D (n_173), .Q
       (\pdt_int[0] [5]));
  DFQD1BWP \pdt_int_reg[0][3] (.CP (clk), .D (n_10), .Q (\pdt_int[0]
       [3]));
  DFQD1BWP \pdt_int_reg[0][7] (.CP (clk), .D (n_165), .Q
       (\pdt_int[0] [7]));
  DFQD1BWP \pdt_int_reg[0][6] (.CP (clk), .D (n_169), .Q
       (\pdt_int[0] [6]));
  DFQD1BWP \pdt_int_reg[0][11] (.CP (clk), .D (n_2), .Q
       (\pdt_int[0] [11]));
  DFQD1BWP \pdt_int_reg[0][0] (.CP (clk), .D (n_13), .Q (\pdt_int[0]
       [0]));
  DFQD1BWP \pdt_int_reg[0][1] (.CP (clk), .D (n_12), .Q (\pdt_int[0]
       [1]));
  DFQD1BWP \pdt_int_reg[0][2] (.CP (clk), .D (n_11), .Q (\pdt_int[0]
       [2]));
  DFQD1BWP \pdt_int_reg[0][12] (.CP (clk), .D (n_1), .Q
       (\pdt_int[0] [12]));
  DFQD1BWP \pdt_int_reg[0][4] (.CP (clk), .D (n_180), .Q
       (\pdt_int[0] [4]));
  DFQD1BWP \a_int_reg[4] (.CP (clk), .D (a[4]), .Q (a_int[4]));
  DFQD1BWP \b_int_reg[6] (.CP (clk), .D (b[6]), .Q (b_int[6]));
  DFQD1BWP \a_int_reg[5] (.CP (clk), .D (a[5]), .Q (a_int[5]));
  DFQD1BWP \b_int_reg[2] (.CP (clk), .D (b[2]), .Q (b_int[2]));
  DFQD1BWP \b_int_reg[0] (.CP (clk), .D (b[0]), .Q (b_int[0]));
  DFQD1BWP \b_int_reg[4] (.CP (clk), .D (b[4]), .Q (b_int[4]));
  DFQD1BWP \a_int_reg[2] (.CP (clk), .D (a[2]), .Q (a_int[2]));
  DFQD1BWP \b_int_reg[1] (.CP (clk), .D (b[1]), .Q (b_int[1]));
  DFQD1BWP \a_int_reg[0] (.CP (clk), .D (a[0]), .Q (a_int[0]));
  DFQD1BWP \a_int_reg[6] (.CP (clk), .D (a[6]), .Q (a_int[6]));
  DFQD1BWP \a_int_reg[1] (.CP (clk), .D (a[1]), .Q (a_int[1]));
  DFQD1BWP \b_int_reg[3] (.CP (clk), .D (b[3]), .Q (b_int[3]));
  DFQD1BWP \b_int_reg[5] (.CP (clk), .D (b[5]), .Q (b_int[5]));
  DFQD1BWP \a_int_reg[3] (.CP (clk), .D (a[3]), .Q (a_int[3]));
  CKND1BWP mul_31_25_g1031(.I (mul_31_25_n_141), .ZN (n_1));
  CKND1BWP mul_31_25_g1032(.I (mul_31_25_n_140), .ZN (n_0));
  FA1D0BWP mul_31_25_g1033__2398(.A (mul_31_25_n_92), .B
       (mul_31_25_n_34), .CI (mul_31_25_n_137), .CO (mul_31_25_n_140),
       .S (mul_31_25_n_141));
  CKND1BWP mul_31_25_g1034(.I (mul_31_25_n_138), .ZN (n_2));
  FA1D0BWP mul_31_25_g1035__5107(.A (n_181), .B (mul_31_25_n_93), .CI
       (mul_31_25_n_134), .CO (mul_31_25_n_137), .S (mul_31_25_n_138));
  CKND1BWP mul_31_25_g1036(.I (mul_31_25_n_135), .ZN (n_3));
  FA1D0BWP mul_31_25_g1037__6260(.A (n_174), .B (n_182), .CI
       (mul_31_25_n_131), .CO (mul_31_25_n_134), .S (mul_31_25_n_135));
  CKND1BWP mul_31_25_g1038(.I (mul_31_25_n_132), .ZN (n_4));
  FA1D0BWP mul_31_25_g1039__4319(.A (n_159), .B (n_175), .CI (n_158),
       .CO (mul_31_25_n_131), .S (mul_31_25_n_132));
  MAOI222D1BWP mul_31_25_g1058__7482(.A (mul_31_25_n_89), .B
       (mul_31_25_n_79), .C (mul_31_25_n_49), .ZN (mul_31_25_n_99));
  XOR3D1BWP mul_31_25_g1059__4733(.A1 (mul_31_25_n_49), .A2
       (mul_31_25_n_79), .A3 (mul_31_25_n_89), .Z (n_10));
  FA1D0BWP mul_31_25_g1060__6161(.A (mul_31_25_n_69), .B
       (mul_31_25_n_60), .CI (mul_31_25_n_64), .CO (mul_31_25_n_96), .S
       (mul_31_25_n_97));
  FA1D0BWP mul_31_25_g1061__9315(.A (mul_31_25_n_73), .B
       (mul_31_25_n_63), .CI (mul_31_25_n_68), .CO (mul_31_25_n_94), .S
       (mul_31_25_n_95));
  FA1D0BWP mul_31_25_g1062__9945(.A (mul_31_25_n_25), .B
       (mul_31_25_n_2), .CI (n_183), .CO (mul_31_25_n_92), .S
       (mul_31_25_n_93));
  FA1D0BWP mul_31_25_g1064__2346(.A (mul_31_25_n_55), .B
       (mul_31_25_n_35), .CI (mul_31_25_n_57), .CO (mul_31_25_n_89), .S
       (n_11));
  FA1D0BWP mul_31_25_g1065__1666(.A (mul_31_25_n_52), .B
       (mul_31_25_n_32), .CI (mul_31_25_n_56), .CO (mul_31_25_n_86), .S
       (mul_31_25_n_87));
  FA1D0BWP mul_31_25_g1066__7410(.A (mul_31_25_n_51), .B
       (mul_31_25_n_6), .CI (mul_31_25_n_61), .CO (mul_31_25_n_84), .S
       (mul_31_25_n_85));
  INVD1BWP mul_31_25_g1069(.I (mul_31_25_n_78), .ZN (mul_31_25_n_79));
  FA1D0BWP mul_31_25_g1070__2398(.A (mul_31_25_n_36), .B
       (mul_31_25_n_33), .CI (mul_31_25_n_58), .CO (mul_31_25_n_77), .S
       (mul_31_25_n_78));
  FA1D0BWP mul_31_25_g1071__5107(.A (mul_31_25_n_40), .B
       (mul_31_25_n_31), .CI (mul_31_25_n_9), .CO (mul_31_25_n_75), .S
       (mul_31_25_n_76));
  FA1D0BWP mul_31_25_g1072__6260(.A (mul_31_25_n_37), .B
       (mul_31_25_n_0), .CI (mul_31_25_n_54), .CO (mul_31_25_n_73), .S
       (mul_31_25_n_74));
  FA1D0BWP mul_31_25_g1073__4319(.A (mul_31_25_n_7), .B
       (mul_31_25_n_4), .CI (mul_31_25_n_53), .CO (mul_31_25_n_71), .S
       (mul_31_25_n_72));
  FA1D0BWP mul_31_25_g1074__8428(.A (mul_31_25_n_27), .B
       (mul_31_25_n_38), .CI (mul_31_25_n_15), .CO (mul_31_25_n_69), .S
       (mul_31_25_n_70));
  FA1D0BWP mul_31_25_g1075__5526(.A (mul_31_25_n_1), .B
       (mul_31_25_n_29), .CI (mul_31_25_n_13), .CO (mul_31_25_n_67), .S
       (mul_31_25_n_68));
  FA1D0BWP mul_31_25_g1076__6783(.A (mul_31_25_n_5), .B
       (mul_31_25_n_8), .CI (mul_31_25_n_12), .CO (mul_31_25_n_65), .S
       (mul_31_25_n_66));
  FA1D0BWP mul_31_25_g1077__3680(.A (mul_31_25_n_39), .B
       (mul_31_25_n_10), .CI (mul_31_25_n_14), .CO (mul_31_25_n_63), .S
       (mul_31_25_n_64));
  AOI21D1BWP mul_31_25_g1078__1617(.A1 (mul_31_25_n_48), .A2
       (mul_31_25_n_47), .B (mul_31_25_n_55), .ZN (n_12));
  XNR2D1BWP mul_31_25_g1079__2802(.A1 (mul_31_25_n_46), .A2
       (mul_31_25_n_24), .ZN (mul_31_25_n_61));
  XNR2D1BWP mul_31_25_g1080__1705(.A1 (mul_31_25_n_45), .A2
       (mul_31_25_n_23), .ZN (mul_31_25_n_60));
  XNR2D1BWP mul_31_25_g1081__5122(.A1 (mul_31_25_n_17), .A2
       (mul_31_25_n_43), .ZN (mul_31_25_n_59));
  XNR2D1BWP mul_31_25_g1082__8246(.A1 (mul_31_25_n_18), .A2
       (mul_31_25_n_22), .ZN (mul_31_25_n_58));
  XOR2D1BWP mul_31_25_g1083__7098(.A1 (mul_31_25_n_19), .A2
       (mul_31_25_n_21), .Z (mul_31_25_n_57));
  XNR2D1BWP mul_31_25_g1084__6131(.A1 (mul_31_25_n_44), .A2
       (mul_31_25_n_20), .ZN (mul_31_25_n_56));
  NR2XD0BWP mul_31_25_g1085__1881(.A1 (mul_31_25_n_48), .A2
       (mul_31_25_n_47), .ZN (mul_31_25_n_55));
  OR2D1BWP mul_31_25_g1086__5115(.A1 (mul_31_25_n_24), .A2
       (mul_31_25_n_46), .Z (mul_31_25_n_54));
  OR2D1BWP mul_31_25_g1087__7482(.A1 (mul_31_25_n_44), .A2
       (mul_31_25_n_20), .Z (mul_31_25_n_53));
  OR2D1BWP mul_31_25_g1088__4733(.A1 (mul_31_25_n_23), .A2
       (mul_31_25_n_45), .Z (mul_31_25_n_52));
  OR2D1BWP mul_31_25_g1089__6161(.A1 (mul_31_25_n_43), .A2
       (mul_31_25_n_17), .Z (mul_31_25_n_51));
  OR2XD1BWP mul_31_25_g1090__9315(.A1 (mul_31_25_n_18), .A2
       (mul_31_25_n_22), .Z (mul_31_25_n_50));
  NR2XD0BWP mul_31_25_g1091__9945(.A1 (mul_31_25_n_19), .A2
       (mul_31_25_n_21), .ZN (mul_31_25_n_49));
  CKND2D1BWP mul_31_25_g1092__2883(.A1 (b_int[0]), .A2 (a_int[1]), .ZN
       (mul_31_25_n_48));
  CKND2D1BWP mul_31_25_g1093__2346(.A1 (b_int[1]), .A2 (a_int[0]), .ZN
       (mul_31_25_n_47));
  CKND2D1BWP mul_31_25_g1094__1666(.A1 (b_int[1]), .A2 (a_int[4]), .ZN
       (mul_31_25_n_46));
  CKND2D1BWP mul_31_25_g1095__7410(.A1 (b_int[1]), .A2 (a_int[5]), .ZN
       (mul_31_25_n_45));
  CKND2D1BWP mul_31_25_g1096__6417(.A1 (a_int[4]), .A2 (b_int[6]), .ZN
       (mul_31_25_n_42));
  CKND2D1BWP mul_31_25_g1097__5477(.A1 (b_int[5]), .A2 (a_int[3]), .ZN
       (mul_31_25_n_41));
  CKND2D1BWP mul_31_25_g1098__2398(.A1 (a_int[3]), .A2 (b_int[6]), .ZN
       (mul_31_25_n_40));
  ND2D1BWP mul_31_25_g1099__5107(.A1 (b_int[1]), .A2 (a_int[6]), .ZN
       (mul_31_25_n_44));
  CKND2D1BWP mul_31_25_g1100__6260(.A1 (b_int[0]), .A2 (a_int[4]), .ZN
       (mul_31_25_n_43));
  CKND2D1BWP mul_31_25_g1101__4319(.A1 (b_int[2]), .A2 (a_int[4]), .ZN
       (mul_31_25_n_39));
  ND2D1BWP mul_31_25_g1102__8428(.A1 (b_int[2]), .A2 (a_int[3]), .ZN
       (mul_31_25_n_38));
  CKND2D1BWP mul_31_25_g1103__5526(.A1 (a_int[1]), .A2 (b_int[5]), .ZN
       (mul_31_25_n_37));
  CKND2D1BWP mul_31_25_g1104__6783(.A1 (a_int[1]), .A2 (b_int[2]), .ZN
       (mul_31_25_n_36));
  AN2XD1BWP mul_31_25_g1105__3680(.A1 (b_int[1]), .A2 (a_int[1]), .Z
       (mul_31_25_n_35));
  ND2D1BWP mul_31_25_g1106__1617(.A1 (a_int[6]), .A2 (b_int[6]), .ZN
       (mul_31_25_n_34));
  ND2D1BWP mul_31_25_g1107__2802(.A1 (a_int[0]), .A2 (b_int[3]), .ZN
       (mul_31_25_n_33));
  ND2D1BWP mul_31_25_g1108__1705(.A1 (a_int[1]), .A2 (b_int[6]), .ZN
       (mul_31_25_n_32));
  ND2D1BWP mul_31_25_g1109__5122(.A1 (b_int[4]), .A2 (a_int[5]), .ZN
       (mul_31_25_n_31));
  ND2D1BWP mul_31_25_g1110__8246(.A1 (b_int[3]), .A2 (a_int[5]), .ZN
       (mul_31_25_n_30));
  ND2D1BWP mul_31_25_g1111__7098(.A1 (b_int[4]), .A2 (a_int[3]), .ZN
       (mul_31_25_n_29));
  ND2D1BWP mul_31_25_g1112__6131(.A1 (b_int[5]), .A2 (a_int[5]), .ZN
       (mul_31_25_n_28));
  CKND2D1BWP mul_31_25_g1113__1881(.A1 (a_int[2]), .A2 (b_int[3]), .ZN
       (mul_31_25_n_27));
  ND2D1BWP mul_31_25_g1114__5115(.A1 (b_int[5]), .A2 (a_int[4]), .ZN
       (mul_31_25_n_26));
  CKND2D1BWP mul_31_25_g1115__7482(.A1 (b_int[5]), .A2 (a_int[6]), .ZN
       (mul_31_25_n_25));
  AN2XD1BWP mul_31_25_g1116__4733(.A1 (b_int[0]), .A2 (a_int[0]), .Z
       (n_13));
  ND2D1BWP mul_31_25_g1117__6161(.A1 (b_int[0]), .A2 (a_int[5]), .ZN
       (mul_31_25_n_24));
  CKND2D1BWP mul_31_25_g1118__9315(.A1 (a_int[1]), .A2 (b_int[4]), .ZN
       (mul_31_25_n_15));
  CKND2D1BWP mul_31_25_g1119__9945(.A1 (b_int[0]), .A2 (a_int[6]), .ZN
       (mul_31_25_n_23));
  CKND2D1BWP mul_31_25_g1120__2883(.A1 (b_int[0]), .A2 (a_int[3]), .ZN
       (mul_31_25_n_22));
  ND2D1BWP mul_31_25_g1121__2346(.A1 (a_int[2]), .A2 (b_int[4]), .ZN
       (mul_31_25_n_14));
  CKND2D1BWP mul_31_25_g1122__1666(.A1 (a_int[0]), .A2 (b_int[2]), .ZN
       (mul_31_25_n_21));
  ND2D1BWP mul_31_25_g1123__7410(.A1 (b_int[2]), .A2 (a_int[5]), .ZN
       (mul_31_25_n_20));
  CKND2D1BWP mul_31_25_g1124__6417(.A1 (b_int[0]), .A2 (a_int[2]), .ZN
       (mul_31_25_n_19));
  ND2D1BWP mul_31_25_g1125__5477(.A1 (a_int[2]), .A2 (b_int[5]), .ZN
       (mul_31_25_n_13));
  CKND2D1BWP mul_31_25_g1126__2398(.A1 (a_int[0]), .A2 (b_int[4]), .ZN
       (mul_31_25_n_12));
  CKND2D1BWP mul_31_25_g1127__5107(.A1 (b_int[1]), .A2 (a_int[2]), .ZN
       (mul_31_25_n_18));
  CKND2D1BWP mul_31_25_g1128__6260(.A1 (b_int[1]), .A2 (a_int[3]), .ZN
       (mul_31_25_n_17));
  CKND2D1BWP mul_31_25_g1129__4319(.A1 (b_int[4]), .A2 (a_int[6]), .ZN
       (mul_31_25_n_11));
  ND2D1BWP mul_31_25_g1130__8428(.A1 (b_int[3]), .A2 (a_int[3]), .ZN
       (mul_31_25_n_10));
  CKND2D1BWP mul_31_25_g1131__5526(.A1 (b_int[3]), .A2 (a_int[6]), .ZN
       (mul_31_25_n_9));
  ND2D1BWP mul_31_25_g1132__6783(.A1 (a_int[1]), .A2 (b_int[3]), .ZN
       (mul_31_25_n_8));
  CKND2D1BWP mul_31_25_g1133__3680(.A1 (b_int[4]), .A2 (a_int[4]), .ZN
       (mul_31_25_n_7));
  ND2D1BWP mul_31_25_g1134__1617(.A1 (a_int[0]), .A2 (b_int[5]), .ZN
       (mul_31_25_n_6));
  CKND2D1BWP mul_31_25_g1135__2802(.A1 (a_int[2]), .A2 (b_int[2]), .ZN
       (mul_31_25_n_5));
  ND2D1BWP mul_31_25_g1136__1705(.A1 (a_int[2]), .A2 (b_int[6]), .ZN
       (mul_31_25_n_4));
  CKND2D1BWP mul_31_25_g1137__5122(.A1 (b_int[2]), .A2 (a_int[6]), .ZN
       (mul_31_25_n_3));
  ND2D1BWP mul_31_25_g1138__8246(.A1 (a_int[5]), .A2 (b_int[6]), .ZN
       (mul_31_25_n_2));
  CKND2D1BWP mul_31_25_g1139__7098(.A1 (b_int[3]), .A2 (a_int[4]), .ZN
       (mul_31_25_n_1));
  ND2D1BWP mul_31_25_g1140__6131(.A1 (a_int[0]), .A2 (b_int[6]), .ZN
       (mul_31_25_n_0));
  CMPE42D1BWP g2(.A (mul_31_25_n_94), .B (mul_31_25_n_72), .C (n_185),
       .CIX (n_163), .D (n_162), .CO (n_158), .COX (n_159), .S (n_160));
  INVD0BWP g3(.I (n_160), .ZN (n_161));
  CMPE42D1BWP g1141(.A (mul_31_25_n_96), .B (mul_31_25_n_87), .C
       (mul_31_25_n_95), .CIX (n_167), .D (n_166), .CO (n_162), .COX
       (n_163), .S (n_164));
  INVD0BWP g1142(.I (n_164), .ZN (n_165));
  CMPE42D1BWP g1143(.A (mul_31_25_n_84), .B (mul_31_25_n_74), .C
       (mul_31_25_n_97), .CIX (n_171), .D (n_170), .CO (n_166), .COX
       (n_167), .S (n_168));
  INVD0BWP g1144(.I (n_168), .ZN (n_169));
  CMPE42D1BWP g1145(.A (mul_31_25_n_70), .B (mul_31_25_n_65), .C
       (mul_31_25_n_85), .CIX (n_178), .D (n_177), .CO (n_170), .COX
       (n_171), .S (n_172));
  INVD0BWP g1146(.I (n_172), .ZN (n_173));
  CMPE42D1BWP g1147(.A (n_186), .B (mul_31_25_n_26), .C
       (mul_31_25_n_76), .CIX (mul_31_25_n_71), .D (n_184), .CO
       (n_174), .COX (n_176), .S (n_175));
  CMPE42D1BWP g1148(.A (mul_31_25_n_59), .B (mul_31_25_n_50), .C
       (mul_31_25_n_66), .CIX (mul_31_25_n_77), .D (mul_31_25_n_99),
       .CO (n_177), .COX (n_178), .S (n_179));
  INVD0BWP g1149(.I (n_179), .ZN (n_180));
  CMPE42D1BWP g1150(.A (mul_31_25_n_42), .B (mul_31_25_n_28), .C
       (mul_31_25_n_11), .CIX (mul_31_25_n_75), .D (n_176), .CO
       (n_181), .COX (n_183), .S (n_182));
  CMPE42D1BWP g1151(.A (mul_31_25_n_3), .B (mul_31_25_n_30), .C
       (mul_31_25_n_41), .CIX (mul_31_25_n_67), .D (mul_31_25_n_86),
       .CO (n_184), .COX (n_186), .S (n_185));
endmodule

