# ####################################################################

#  Created by Genus(TM) Synthesis Solution 19.11-s087_1 on Wed Aug 03 14:30:17 CEST 2022

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design adder

set_clock_gating_check -setup 0.0 
set_input_delay -add_delay 0.1 [get_ports {input1[31]}]
set_input_delay -add_delay 0.1 [get_ports {input1[30]}]
set_input_delay -add_delay 0.1 [get_ports {input1[29]}]
set_input_delay -add_delay 0.1 [get_ports {input1[28]}]
set_input_delay -add_delay 0.1 [get_ports {input1[27]}]
set_input_delay -add_delay 0.1 [get_ports {input1[26]}]
set_input_delay -add_delay 0.1 [get_ports {input1[25]}]
set_input_delay -add_delay 0.1 [get_ports {input1[24]}]
set_input_delay -add_delay 0.1 [get_ports {input1[23]}]
set_input_delay -add_delay 0.1 [get_ports {input1[22]}]
set_input_delay -add_delay 0.1 [get_ports {input1[21]}]
set_input_delay -add_delay 0.1 [get_ports {input1[20]}]
set_input_delay -add_delay 0.1 [get_ports {input1[19]}]
set_input_delay -add_delay 0.1 [get_ports {input1[18]}]
set_input_delay -add_delay 0.1 [get_ports {input1[17]}]
set_input_delay -add_delay 0.1 [get_ports {input1[16]}]
set_input_delay -add_delay 0.1 [get_ports {input1[15]}]
set_input_delay -add_delay 0.1 [get_ports {input1[14]}]
set_input_delay -add_delay 0.1 [get_ports {input1[13]}]
set_input_delay -add_delay 0.1 [get_ports {input1[12]}]
set_input_delay -add_delay 0.1 [get_ports {input1[11]}]
set_input_delay -add_delay 0.1 [get_ports {input1[10]}]
set_input_delay -add_delay 0.1 [get_ports {input1[9]}]
set_input_delay -add_delay 0.1 [get_ports {input1[8]}]
set_input_delay -add_delay 0.1 [get_ports {input1[7]}]
set_input_delay -add_delay 0.1 [get_ports {input1[6]}]
set_input_delay -add_delay 0.1 [get_ports {input1[5]}]
set_input_delay -add_delay 0.1 [get_ports {input1[4]}]
set_input_delay -add_delay 0.1 [get_ports {input1[3]}]
set_input_delay -add_delay 0.1 [get_ports {input1[2]}]
set_input_delay -add_delay 0.1 [get_ports {input1[1]}]
set_input_delay -add_delay 0.1 [get_ports {input1[0]}]
set_input_delay -add_delay 0.1 [get_ports {input2[31]}]
set_input_delay -add_delay 0.1 [get_ports {input2[30]}]
set_input_delay -add_delay 0.1 [get_ports {input2[29]}]
set_input_delay -add_delay 0.1 [get_ports {input2[28]}]
set_input_delay -add_delay 0.1 [get_ports {input2[27]}]
set_input_delay -add_delay 0.1 [get_ports {input2[26]}]
set_input_delay -add_delay 0.1 [get_ports {input2[25]}]
set_input_delay -add_delay 0.1 [get_ports {input2[24]}]
set_input_delay -add_delay 0.1 [get_ports {input2[23]}]
set_input_delay -add_delay 0.1 [get_ports {input2[22]}]
set_input_delay -add_delay 0.1 [get_ports {input2[21]}]
set_input_delay -add_delay 0.1 [get_ports {input2[20]}]
set_input_delay -add_delay 0.1 [get_ports {input2[19]}]
set_input_delay -add_delay 0.1 [get_ports {input2[18]}]
set_input_delay -add_delay 0.1 [get_ports {input2[17]}]
set_input_delay -add_delay 0.1 [get_ports {input2[16]}]
set_input_delay -add_delay 0.1 [get_ports {input2[15]}]
set_input_delay -add_delay 0.1 [get_ports {input2[14]}]
set_input_delay -add_delay 0.1 [get_ports {input2[13]}]
set_input_delay -add_delay 0.1 [get_ports {input2[12]}]
set_input_delay -add_delay 0.1 [get_ports {input2[11]}]
set_input_delay -add_delay 0.1 [get_ports {input2[10]}]
set_input_delay -add_delay 0.1 [get_ports {input2[9]}]
set_input_delay -add_delay 0.1 [get_ports {input2[8]}]
set_input_delay -add_delay 0.1 [get_ports {input2[7]}]
set_input_delay -add_delay 0.1 [get_ports {input2[6]}]
set_input_delay -add_delay 0.1 [get_ports {input2[5]}]
set_input_delay -add_delay 0.1 [get_ports {input2[4]}]
set_input_delay -add_delay 0.1 [get_ports {input2[3]}]
set_input_delay -add_delay 0.1 [get_ports {input2[2]}]
set_input_delay -add_delay 0.1 [get_ports {input2[1]}]
set_input_delay -add_delay 0.1 [get_ports {input2[0]}]
set_output_delay -add_delay 0.1 [get_ports {sum[31]}]
set_output_delay -add_delay 0.1 [get_ports {sum[30]}]
set_output_delay -add_delay 0.1 [get_ports {sum[29]}]
set_output_delay -add_delay 0.1 [get_ports {sum[28]}]
set_output_delay -add_delay 0.1 [get_ports {sum[27]}]
set_output_delay -add_delay 0.1 [get_ports {sum[26]}]
set_output_delay -add_delay 0.1 [get_ports {sum[25]}]
set_output_delay -add_delay 0.1 [get_ports {sum[24]}]
set_output_delay -add_delay 0.1 [get_ports {sum[23]}]
set_output_delay -add_delay 0.1 [get_ports {sum[22]}]
set_output_delay -add_delay 0.1 [get_ports {sum[21]}]
set_output_delay -add_delay 0.1 [get_ports {sum[20]}]
set_output_delay -add_delay 0.1 [get_ports {sum[19]}]
set_output_delay -add_delay 0.1 [get_ports {sum[18]}]
set_output_delay -add_delay 0.1 [get_ports {sum[17]}]
set_output_delay -add_delay 0.1 [get_ports {sum[16]}]
set_output_delay -add_delay 0.1 [get_ports {sum[15]}]
set_output_delay -add_delay 0.1 [get_ports {sum[14]}]
set_output_delay -add_delay 0.1 [get_ports {sum[13]}]
set_output_delay -add_delay 0.1 [get_ports {sum[12]}]
set_output_delay -add_delay 0.1 [get_ports {sum[11]}]
set_output_delay -add_delay 0.1 [get_ports {sum[10]}]
set_output_delay -add_delay 0.1 [get_ports {sum[9]}]
set_output_delay -add_delay 0.1 [get_ports {sum[8]}]
set_output_delay -add_delay 0.1 [get_ports {sum[7]}]
set_output_delay -add_delay 0.1 [get_ports {sum[6]}]
set_output_delay -add_delay 0.1 [get_ports {sum[5]}]
set_output_delay -add_delay 0.1 [get_ports {sum[4]}]
set_output_delay -add_delay 0.1 [get_ports {sum[3]}]
set_output_delay -add_delay 0.1 [get_ports {sum[2]}]
set_output_delay -add_delay 0.1 [get_ports {sum[1]}]
set_output_delay -add_delay 0.1 [get_ports {sum[0]}]
