// Generated by stratus_hls 19.25-s100  (93142.260418)
// Wed Sep  7 10:39:56 2022
// from fir.cc
#ifndef CYNTH_PART_fir_fir_rtl_h
#define CYNTH_PART_fir_fir_rtl_h

#include "systemc.h"
/* Include declarations of instantiated parts. */
#include "fir_logic_1.h"


/* Declaration of the synthesized module. */
struct fir : public sc_module {
  sc_in<bool > clk;
  sc_in<bool > rst;
  sc_in<sc_uint<8> > coeffs_table_0;
  sc_in<sc_uint<8> > coeffs_table_1;
  sc_in<sc_uint<8> > coeffs_table_2;
  sc_in<sc_uint<8> > coeffs_table_3;
  sc_in<sc_uint<8> > coeffs_table_4;
  sc_in<sc_uint<8> > coeffs_table_5;
  sc_in<sc_uint<8> > coeffs_table_6;
  sc_in<sc_uint<8> > coeffs_table_7;
  sc_out<bool > din_busy;
  sc_in<bool > din_vld;
  sc_in<sc_uint<8> > din_data;
  sc_in<bool > dout_busy;
  sc_out<bool > dout_vld;
  sc_out<sc_uint<11> > dout_data;
  fir( sc_module_name name );
  SC_HAS_PROCESS(fir);
  fir_logic_1 *fir_logic_1_1;
};

#endif
