// Generated by stratus_hls 19.25-s100  (93142.260418)
// Tue Sep  6 17:30:11 2022
// from fir.cc
#include "fir_rtl.h"

struct fir;
fir::fir(sc_module_name name) : sc_module(name) 
    ,clk("clk")
    ,rst("rst")
    ,coeffs_table_0("coeffs_table_0")
    ,coeffs_table_1("coeffs_table_1")
    ,coeffs_table_2("coeffs_table_2")
    ,coeffs_table_3("coeffs_table_3")
    ,coeffs_table_4("coeffs_table_4")
    ,coeffs_table_5("coeffs_table_5")
    ,coeffs_table_6("coeffs_table_6")
    ,coeffs_table_7("coeffs_table_7")
    ,din_busy("din_busy")
    ,din_vld("din_vld")
    ,din_data("din_data")
    ,dout_busy("dout_busy")
    ,dout_vld("dout_vld")
    ,dout_data("dout_data")
    ,dout_m_req_m_prev_trig_req("dout_m_req_m_prev_trig_req")
    ,fir_Xor_1Ux1U_1U_1_4_out1("fir_Xor_1Ux1U_1U_1_4_out1")
    ,dout_m_unacked_req("dout_m_unacked_req")
    ,fir_Or_1Ux1U_1U_4_5_out1("fir_Or_1Ux1U_1U_4_5_out1")
    ,fir_And_1Ux1U_1U_4_27_out1("fir_And_1Ux1U_1U_4_27_out1")
    ,fir_And_1Ux1U_1U_4_25_out1("fir_And_1Ux1U_1U_4_25_out1")
    ,fir_Not_1U_1U_4_24_out1("fir_Not_1U_1U_4_24_out1")
    ,fir_And_1Ux1U_1U_4_26_out1("fir_And_1Ux1U_1U_4_26_out1")
    ,fir_N_Muxb_1_2_8_4_1_out1("fir_N_Muxb_1_2_8_4_1_out1")
    ,din_m_unvalidated_req("din_m_unvalidated_req")
    ,fir_gen_busy_r_1_2_gnew_req("fir_gen_busy_r_1_2_gnew_req")
    ,fir_gen_busy_r_1_2_gen_busy_din_m_data_is_invalid_next("fir_gen_busy_r_1_2_gen_busy_din_m_data_is_invalid_next")
    ,fir_gen_busy_r_1_2_gdiv("fir_gen_busy_r_1_2_gdiv")
    ,fir_gen_busy_r_1_2_gnew_busy("fir_gen_busy_r_1_2_gnew_busy")
    ,din_m_data_is_valid("din_m_data_is_valid")
    ,t_18("t_18")
    ,t_15("t_15")
    ,rdy_0("rdy_0")
    ,vld_0("vld_0")
    ,rdy_1("rdy_1")
    ,t_11("t_11")
    ,fir_gen_busy_r_1_2_out1("fir_gen_busy_r_1_2_out1")
    ,vld_1("vld_1")
    ,rdy_2("rdy_2")
    ,global_state("global_state")
    ,t_13("t_13")
    ,cycle2_state("cycle2_state")
    ,fir_And_1Ux1U_1U_1_6_out1("fir_And_1Ux1U_1U_1_6_out1")
    ,fir_Mul_8Ux8U_11U_4_22_out1("fir_Mul_8Ux8U_11U_4_22_out1")
    ,din_m_stall_reg_full("din_m_stall_reg_full")
    ,din_m_stall_reg("din_m_stall_reg")
    ,fir_Mul_8Ux8U_11U_4_19_out1("fir_Mul_8Ux8U_11U_4_19_out1")
    ,fir_Add_11Ux11U_11U_4_18_out1("fir_Add_11Ux11U_11U_4_18_out1")
    ,fir_Mul_8Ux8U_11U_4_17_out1("fir_Mul_8Ux8U_11U_4_17_out1")
    ,fir_Add_11Ux11U_11U_4_16_out1("fir_Add_11Ux11U_11U_4_16_out1")
    ,fir_Mul_8Ux8U_11U_4_15_out1("fir_Mul_8Ux8U_11U_4_15_out1")
    ,fir_Add_11Ux11U_11U_4_14_out1("fir_Add_11Ux11U_11U_4_14_out1")
    ,fir_Mul_8Ux8U_11U_4_13_out1("fir_Mul_8Ux8U_11U_4_13_out1")
    ,fir_Add_11Ux11U_11U_4_12_out1("fir_Add_11Ux11U_11U_4_12_out1")
    ,fir_Mul_8Ux8U_11U_4_11_out1("fir_Mul_8Ux8U_11U_4_11_out1")
    ,fir_Add_11Ux11U_11U_4_10_out1("fir_Add_11Ux11U_11U_4_10_out1")
    ,fir_Mul_8Ux8U_11U_4_9_out1("fir_Mul_8Ux8U_11U_4_9_out1")
    ,fir_Mul_8Ux8U_11U_4_8_out1("fir_Mul_8Ux8U_11U_4_8_out1")
    ,s_reg_9("s_reg_9")
    ,s_reg_8("s_reg_8")
    ,fir_Add_11Ux11U_11U_4_20_out1("fir_Add_11Ux11U_11U_4_20_out1")
    ,s_reg_14("s_reg_14")
    ,en_0("en_0")
    ,s_reg_13("s_reg_13")
    ,s_reg_12("s_reg_12")
    ,s_reg_11("s_reg_11")
    ,s_reg_10("s_reg_10")
    ,shift_reg_7_mi12("shift_reg_7_mi12")
    ,cycle1_state("cycle1_state")
    ,fir_N_Mux_8_2_10_4_21_out1("fir_N_Mux_8_2_10_4_21_out1")
    ,fir_Not_1U_1U_1_7_out1("fir_Not_1U_1U_1_7_out1")
    ,dout_m_req_m_trig_req("dout_m_req_m_trig_req")
    ,din_m_stalling("din_m_stalling")
    ,t_2("t_2")
    ,t_3("t_3")
    ,t_1("t_1")
    ,t_0("t_0")
    ,din_m_busy_req_0("din_m_busy_req_0")
    ,fir_Add_11Ux11U_11U_4_23_out1("fir_Add_11Ux11U_11U_4_23_out1")
    ,dout_data_slice("dout_data_slice")
    ,en_1("en_1")
{
  SC_METHOD(drive_dout_data_slice);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(drive_din_m_busy_req_0);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(drive_din_m_stalling);
  sensitive << ( t_2 );
  sensitive << ( t_3 );

  SC_METHOD(drive_dout_m_req_m_trig_req);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(drive_shift_reg_7_mi12);
  sensitive << ( cycle1_state );
  sensitive << ( fir_N_Mux_8_2_10_4_21_out1 );

  SC_METHOD(drive_s_reg_10);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_11);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_12);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_13);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_14);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_8);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_9);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(fir_Mul_8Ux8U_11U_4_8);
  sensitive << ( s_reg_9 );
  sensitive << ( coeffs_table_1 );

  SC_METHOD(fir_Mul_8Ux8U_11U_4_9);
  sensitive << ( s_reg_8 );
  sensitive << ( coeffs_table_0 );

  SC_METHOD(fir_Add_11Ux11U_11U_4_10);
  sensitive << ( fir_Mul_8Ux8U_11U_4_8_out1 );
  sensitive << ( fir_Mul_8Ux8U_11U_4_9_out1 );

  SC_METHOD(fir_Mul_8Ux8U_11U_4_11);
  sensitive << ( s_reg_10 );
  sensitive << ( coeffs_table_2 );

  SC_METHOD(fir_Add_11Ux11U_11U_4_12);
  sensitive << ( fir_Add_11Ux11U_11U_4_10_out1 );
  sensitive << ( fir_Mul_8Ux8U_11U_4_11_out1 );

  SC_METHOD(fir_Mul_8Ux8U_11U_4_13);
  sensitive << ( s_reg_11 );
  sensitive << ( coeffs_table_3 );

  SC_METHOD(fir_Add_11Ux11U_11U_4_14);
  sensitive << ( fir_Add_11Ux11U_11U_4_12_out1 );
  sensitive << ( fir_Mul_8Ux8U_11U_4_13_out1 );

  SC_METHOD(fir_Mul_8Ux8U_11U_4_15);
  sensitive << ( s_reg_12 );
  sensitive << ( coeffs_table_4 );

  SC_METHOD(fir_Add_11Ux11U_11U_4_16);
  sensitive << ( fir_Add_11Ux11U_11U_4_14_out1 );
  sensitive << ( fir_Mul_8Ux8U_11U_4_15_out1 );

  SC_METHOD(fir_Mul_8Ux8U_11U_4_17);
  sensitive << ( s_reg_13 );
  sensitive << ( coeffs_table_5 );

  SC_METHOD(fir_Add_11Ux11U_11U_4_18);
  sensitive << ( fir_Add_11Ux11U_11U_4_16_out1 );
  sensitive << ( fir_Mul_8Ux8U_11U_4_17_out1 );

  SC_METHOD(fir_Mul_8Ux8U_11U_4_19);
  sensitive << ( shift_reg_7_mi12 );
  sensitive << ( coeffs_table_6 );

  SC_METHOD(fir_Add_11Ux11U_11U_4_20);
  sensitive << ( fir_Add_11Ux11U_11U_4_18_out1 );
  sensitive << ( fir_Mul_8Ux8U_11U_4_19_out1 );

  SC_METHOD(fir_N_Mux_8_2_10_4_21);
  sensitive << ( din_m_stall_reg_full );
  sensitive << ( din_m_stall_reg );
  sensitive << ( din_data );

  SC_METHOD(fir_Mul_8Ux8U_11U_4_22);
  sensitive << ( fir_N_Mux_8_2_10_4_21_out1 );
  sensitive << ( coeffs_table_7 );

  SC_METHOD(fir_Add_11Ux11U_11U_4_23);
  sensitive << ( s_reg_14 );
  sensitive << ( fir_Mul_8Ux8U_11U_4_22_out1 );

  SC_METHOD(drive_rdy_2);
  sensitive << ( global_state );
  sensitive << ( t_13 );
  sensitive << ( cycle2_state );
  sensitive << ( fir_And_1Ux1U_1U_1_6_out1 );

  SC_METHOD(drive_vld_1);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(drive_rdy_1);
  sensitive << ( global_state );
  sensitive << ( t_11 );
  sensitive << ( cycle1_state );
  sensitive << ( rdy_2 );
  sensitive << ( vld_1 );
  sensitive << ( fir_gen_busy_r_1_2_out1 );

  SC_METHOD(drive_vld_0);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(drive_rdy_0);
  sensitive << ( rdy_1 );
  sensitive << ( vld_0 );

  SC_METHOD(drive_en_0);
  sensitive << ( global_state );
  sensitive << ( rdy_0 );

  SC_METHOD(drive_en_1);
  sensitive << ( global_state );
  sensitive << ( rdy_1 );
  sensitive << ( vld_0 );

  SC_METHOD(drive_cycle1_state);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(drive_cycle2_state);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(drive_global_state);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(drive_t_0);
  sensitive << ( global_state );
  sensitive << ( en_1 );
  sensitive << ( cycle1_state );
  sensitive << ( en_0 );

  SC_METHOD(drive_t_1);
  sensitive << ( global_state );
  sensitive << ( en_0 );

  SC_METHOD(drive_t_2);
  sensitive << ( global_state );
  sensitive << ( en_1 );
  sensitive << ( cycle1_state );

  SC_METHOD(drive_t_3);
  sensitive << ( en_1 );
  sensitive << ( cycle1_state );
  sensitive << ( global_state );

  SC_METHOD(drive_t_11);
  sensitive << ( cycle1_state );

  SC_METHOD(drive_t_13);
  sensitive << ( cycle2_state );

  SC_METHOD(drive_t_15);
  sensitive << ( global_state );

  SC_METHOD(drive_t_18);
  sensitive << ( global_state );
  sensitive << ( en_1 );

  SC_METHOD(drive_din_busy);
  sensitive << ( fir_gen_busy_r_1_2_out1 );

  SC_METHOD(drive_din_m_data_is_valid);
  sensitive << ( fir_gen_busy_r_1_2_out1 );

  SC_METHOD(fir_gen_busy_r_1_2_p9);
  sensitive << ( fir_gen_busy_r_1_2_gen_busy_din_m_data_is_invalid_next );
  sensitive << ( fir_gen_busy_r_1_2_gdiv );
  sensitive << ( fir_gen_busy_r_1_2_gnew_busy );

  SC_METHOD(fir_gen_busy_r_1_2_p8);
  sensitive << ( fir_gen_busy_r_1_2_gdiv );

  SC_METHOD(fir_gen_busy_r_1_2_p7);
  sensitive << ( din_m_stall_reg_full );
  sensitive << ( fir_gen_busy_r_1_2_gnew_req );
  sensitive << ( din_vld );

  SC_METHOD(fir_gen_busy_r_1_2_p6);
  sensitive << ( din_m_stall_reg_full );
  sensitive << ( fir_gen_busy_r_1_2_gnew_req );

  SC_METHOD(fir_gen_busy_r_1_2_p5);
  sensitive << ( din_vld );
  sensitive << ( din_m_unvalidated_req );
  sensitive << ( din_m_busy_req_0 );

  SC_METHOD(drive_din_m_unvalidated_req);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(fir_N_Muxb_1_2_8_4_1);
  sensitive << ( din_m_busy_req_0 );
  sensitive << ( din_m_unvalidated_req );
  sensitive << ( din_vld );

  SC_METHOD(drive_din_m_stall_reg);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(fir_Not_1U_1U_4_24);
  sensitive << ( din_m_stall_reg_full );

  SC_METHOD(fir_And_1Ux1U_1U_4_25);
  sensitive << ( din_m_stalling );
  sensitive << ( din_m_data_is_valid );

  SC_METHOD(fir_And_1Ux1U_1U_4_26);
  sensitive << ( fir_Not_1U_1U_4_24_out1 );
  sensitive << ( fir_And_1Ux1U_1U_4_25_out1 );

  SC_METHOD(drive_din_m_stall_reg_full);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(fir_And_1Ux1U_1U_4_27);
  sensitive << ( din_m_stalling );
  sensitive << ( din_m_data_is_valid );

  SC_METHOD(drive_dout_vld);
  sensitive << ( fir_Or_1Ux1U_1U_4_5_out1 );

  SC_METHOD(fir_Or_1Ux1U_1U_4_5);
  sensitive << ( fir_Xor_1Ux1U_1U_1_4_out1 );
  sensitive << ( dout_m_unacked_req );

  SC_METHOD(drive_dout_m_unacked_req);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(fir_And_1Ux1U_1U_1_6);
  sensitive << ( dout_vld );
  sensitive << ( dout_busy );

  SC_METHOD(fir_Xor_1Ux1U_1U_1_4);
  sensitive << ( dout_m_req_m_prev_trig_req );
  sensitive << ( dout_m_req_m_trig_req );

  SC_METHOD(drive_dout_m_req_m_prev_trig_req);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(fir_Not_1U_1U_1_7);
  sensitive << ( dout_m_req_m_trig_req );

  SC_METHOD(drive_dout_data);
  sensitive << ( dout_data_slice );

}
// resource: regr_en_7
void fir::drive_dout_data_slice(){
  switch( (sc_uint<1>)(en_1.read()) ) {
  case 1ULL: 
    dout_data_slice = (sc_uint<7> ) (fir_Add_11Ux11U_11U_4_23_out1.read().range(
                      10,4));
    break;
  case 0ULL: 
    break;
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_ss_1
void fir::drive_din_m_busy_req_0(){
  if ( (rst.read() == 0ULL) ) {
    din_m_busy_req_0 = 1ULL;
  } else {
    switch( (sc_uint<2>)((sc_uint<2> )(sc_bv<2>)((sc_bv<1>)(t_1.read()), 
            (sc_bv<1>)(t_0.read()))) ) {
    case 1ULL: 
      din_m_busy_req_0 = 1ULL;
      break;
    case 2ULL: 
      din_m_busy_req_0 = 0ULL;
      break;
    }
  }
}
// resource: mux_1bx2i2c
void fir::drive_din_m_stalling(){
  switch( (sc_uint<2>)((sc_uint<2> )(sc_bv<2>)((sc_bv<1>)(t_3.read()), 
          (sc_bv<1>)(t_2.read()))) ) {
  default:
    din_m_stalling = 0ULL;
    break;
  case 2ULL: 
    din_m_stalling = 1ULL;
    break;
  }
}
// resource: regr_en_sc_1
void fir::drive_dout_m_req_m_trig_req(){
  if ( (rst.read() == 0ULL) ) {
    dout_m_req_m_trig_req = 0ULL;
  } else {
    switch( (sc_uint<1>)(t_2.read()) ) {
    case 1ULL: 
      dout_m_req_m_trig_req = (sc_uint<1> ) (fir_Not_1U_1U_1_7_out1.read());
      break;
    case 0ULL: 
      break;
    }
  }
}
// resource: mux_8bx2i1c
void fir::drive_shift_reg_7_mi12(){
  if ( cycle1_state.read() ) {
    shift_reg_7_mi12 = 0ULL;
  } else {
    shift_reg_7_mi12 = fir_N_Mux_8_2_10_4_21_out1.read();
  }
}
// resource: regr_en_sc_8
void fir::drive_s_reg_10(){
  if ( (rst.read() == 0ULL) ) {
    s_reg_10 = 0ULL;
  } else {
    switch( (sc_uint<1>)(t_1.read()) ) {
    case 1ULL: 
      s_reg_10 = s_reg_11.read();
      break;
    case 0ULL: 
      break;
    }
  }
}
// resource: regr_en_sc_8
void fir::drive_s_reg_11(){
  if ( (rst.read() == 0ULL) ) {
    s_reg_11 = 0ULL;
  } else {
    switch( (sc_uint<1>)(t_1.read()) ) {
    case 1ULL: 
      s_reg_11 = s_reg_12.read();
      break;
    case 0ULL: 
      break;
    }
  }
}
// resource: regr_en_sc_8
void fir::drive_s_reg_12(){
  if ( (rst.read() == 0ULL) ) {
    s_reg_12 = 0ULL;
  } else {
    switch( (sc_uint<1>)(t_1.read()) ) {
    case 1ULL: 
      s_reg_12 = s_reg_13.read();
      break;
    case 0ULL: 
      break;
    }
  }
}
// resource: regr_en_sc_8
void fir::drive_s_reg_13(){
  if ( (rst.read() == 0ULL) ) {
    s_reg_13 = 0ULL;
  } else {
    switch( (sc_uint<1>)(t_1.read()) ) {
    case 1ULL: 
      s_reg_13 = shift_reg_7_mi12.read();
      break;
    case 0ULL: 
      break;
    }
  }
}
// resource: regr_en_11
void fir::drive_s_reg_14(){
  switch( (sc_uint<1>)(en_0.read()) ) {
  case 1ULL: 
    s_reg_14 = fir_Add_11Ux11U_11U_4_20_out1.read();
    break;
  case 0ULL: 
    break;
  }
}
// resource: regr_en_sc_8
void fir::drive_s_reg_8(){
  if ( (rst.read() == 0ULL) ) {
    s_reg_8 = 0ULL;
  } else {
    switch( (sc_uint<1>)(t_1.read()) ) {
    case 1ULL: 
      s_reg_8 = s_reg_9.read();
      break;
    case 0ULL: 
      break;
    }
  }
}
// resource: regr_en_sc_8
void fir::drive_s_reg_9(){
  if ( (rst.read() == 0ULL) ) {
    s_reg_9 = 0ULL;
  } else {
    switch( (sc_uint<1>)(t_1.read()) ) {
    case 1ULL: 
      s_reg_9 = s_reg_10.read();
      break;
    case 0ULL: 
      break;
    }
  }
}
// resource: fir_Mul_8Ux8U_11U_4  instance: fir_Mul_8Ux8U_11U_4_8
void fir::fir_Mul_8Ux8U_11U_4_8(){
  fir_Mul_8Ux8U_11U_4_8_out1 = coeffs_table_1.read() * s_reg_9.read();
}
// resource: fir_Mul_8Ux8U_11U_4  instance: fir_Mul_8Ux8U_11U_4_9
void fir::fir_Mul_8Ux8U_11U_4_9(){
  fir_Mul_8Ux8U_11U_4_9_out1 = coeffs_table_0.read() * s_reg_8.read();
}
// resource: fir_Add_11Ux11U_11U_4  instance: fir_Add_11Ux11U_11U_4_10
void fir::fir_Add_11Ux11U_11U_4_10(){
  fir_Add_11Ux11U_11U_4_10_out1 = (fir_Mul_8Ux8U_11U_4_9_out1.read() + 
                                  fir_Mul_8Ux8U_11U_4_8_out1.read());
}
// resource: fir_Mul_8Ux8U_11U_4  instance: fir_Mul_8Ux8U_11U_4_11
void fir::fir_Mul_8Ux8U_11U_4_11(){
  fir_Mul_8Ux8U_11U_4_11_out1 = coeffs_table_2.read() * s_reg_10.read();
}
// resource: fir_Add_11Ux11U_11U_4  instance: fir_Add_11Ux11U_11U_4_12
void fir::fir_Add_11Ux11U_11U_4_12(){
  fir_Add_11Ux11U_11U_4_12_out1 = (fir_Mul_8Ux8U_11U_4_11_out1.read() + 
                                  fir_Add_11Ux11U_11U_4_10_out1.read());
}
// resource: fir_Mul_8Ux8U_11U_4  instance: fir_Mul_8Ux8U_11U_4_13
void fir::fir_Mul_8Ux8U_11U_4_13(){
  fir_Mul_8Ux8U_11U_4_13_out1 = coeffs_table_3.read() * s_reg_11.read();
}
// resource: fir_Add_11Ux11U_11U_4  instance: fir_Add_11Ux11U_11U_4_14
void fir::fir_Add_11Ux11U_11U_4_14(){
  fir_Add_11Ux11U_11U_4_14_out1 = (fir_Mul_8Ux8U_11U_4_13_out1.read() + 
                                  fir_Add_11Ux11U_11U_4_12_out1.read());
}
// resource: fir_Mul_8Ux8U_11U_4  instance: fir_Mul_8Ux8U_11U_4_15
void fir::fir_Mul_8Ux8U_11U_4_15(){
  fir_Mul_8Ux8U_11U_4_15_out1 = coeffs_table_4.read() * s_reg_12.read();
}
// resource: fir_Add_11Ux11U_11U_4  instance: fir_Add_11Ux11U_11U_4_16
void fir::fir_Add_11Ux11U_11U_4_16(){
  fir_Add_11Ux11U_11U_4_16_out1 = (fir_Mul_8Ux8U_11U_4_15_out1.read() + 
                                  fir_Add_11Ux11U_11U_4_14_out1.read());
}
// resource: fir_Mul_8Ux8U_11U_4  instance: fir_Mul_8Ux8U_11U_4_17
void fir::fir_Mul_8Ux8U_11U_4_17(){
  fir_Mul_8Ux8U_11U_4_17_out1 = coeffs_table_5.read() * s_reg_13.read();
}
// resource: fir_Add_11Ux11U_11U_4  instance: fir_Add_11Ux11U_11U_4_18
void fir::fir_Add_11Ux11U_11U_4_18(){
  fir_Add_11Ux11U_11U_4_18_out1 = (fir_Mul_8Ux8U_11U_4_17_out1.read() + 
                                  fir_Add_11Ux11U_11U_4_16_out1.read());
}
// resource: fir_Mul_8Ux8U_11U_4  instance: fir_Mul_8Ux8U_11U_4_19
void fir::fir_Mul_8Ux8U_11U_4_19(){
  fir_Mul_8Ux8U_11U_4_19_out1 = coeffs_table_6.read() * shift_reg_7_mi12.read();
}
// resource: fir_Add_11Ux11U_11U_4  instance: fir_Add_11Ux11U_11U_4_20
void fir::fir_Add_11Ux11U_11U_4_20(){
  fir_Add_11Ux11U_11U_4_20_out1 = (fir_Mul_8Ux8U_11U_4_19_out1.read() + 
                                  fir_Add_11Ux11U_11U_4_18_out1.read());
}
// resource: fir_N_Mux_8_2_10_4
void fir::fir_N_Mux_8_2_10_4_21(){
  if ( din_m_stall_reg_full.read() ) {
    fir_N_Mux_8_2_10_4_21_out1 = din_m_stall_reg.read();
  } else {
    fir_N_Mux_8_2_10_4_21_out1 = din_data.read();
  }
}
// resource: fir_Mul_8Ux8U_11U_4  instance: fir_Mul_8Ux8U_11U_4_22
void fir::fir_Mul_8Ux8U_11U_4_22(){
  fir_Mul_8Ux8U_11U_4_22_out1 = coeffs_table_7.read() * 
                                fir_N_Mux_8_2_10_4_21_out1.read();
}
// resource: fir_Add_11Ux11U_11U_4  instance: fir_Add_11Ux11U_11U_4_23
void fir::fir_Add_11Ux11U_11U_4_23(){
  fir_Add_11Ux11U_11U_4_23_out1 = (fir_Mul_8Ux8U_11U_4_22_out1.read() + s_reg_14
                                  .read());
}
// resource: mux_1bx3i2c
void fir::drive_rdy_2(){
  if ( global_state.read() ) {
    switch( (sc_uint<2>)((sc_uint<2> )(sc_bv<2>)((sc_bv<1>)(cycle2_state.read())
            , 
            (sc_bv<1>)(t_13.read()))) ) {
    default:
      rdy_2 = 1ULL;
      break;
    case 1ULL: 
      rdy_2 = !fir_And_1Ux1U_1U_1_6_out1.read();
      break;
    }
  } else {
    rdy_2 = 0ULL;
  }
}
// resource: mux_1bx2i1c
// resource: regr_1
void fir::drive_vld_1(){
  switch( (sc_uint<1>)(global_state.read()) ) {
  case 1ULL: 
    vld_1 = en_1.read() | vld_1.read() & !rdy_2.read();
    break;
  case 0ULL: 
    vld_1 = 0ULL;
    break;
  }
}
// resource: mux_1bx3i1c
void fir::drive_rdy_1(){
  if ( global_state.read() ) {
    switch( (sc_uint<2>)((sc_uint<2> )(sc_bv<2>)((sc_bv<1>)(cycle1_state.read())
            , 
            (sc_bv<1>)(t_11.read()))) ) {
    default:
      rdy_1 = !vld_1.read() | rdy_2.read();
      break;
    case 1ULL: 
      rdy_1 = ( !vld_1.read() | rdy_2.read() ) & !(sc_uint<1> )
              fir_gen_busy_r_1_2_out1.read();
      break;
    }
  } else {
    rdy_1 = 0ULL;
  }
}
// resource: mux_1bx2i1c
// resource: regr_1
void fir::drive_vld_0(){
  switch( (sc_uint<1>)(global_state.read()) ) {
  case 1ULL: 
    vld_0 = en_0.read() | vld_0.read() & !rdy_1.read();
    break;
  case 0ULL: 
    vld_0 = 0ULL;
    break;
  }
}
void fir::drive_rdy_0(){
  rdy_0 = !vld_0.read() | rdy_1.read();
}
// resource: mux_1bx2i1c
void fir::drive_en_0(){
  if ( global_state.read() ) {
    en_0 = rdy_0.read();
  } else {
    en_0 = 0ULL;
  }
}
// resource: mux_1bx2i1c
void fir::drive_en_1(){
  if ( global_state.read() ) {
    en_1 = vld_0.read() & rdy_1.read();
  } else {
    en_1 = 0ULL;
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_1
void fir::drive_cycle1_state(){
  switch( (sc_uint<2>)((sc_uint<2> )(sc_bv<2>)((sc_bv<1>)(t_1.read()), 
          (sc_bv<1>)(t_15.read()))) ) {
  case 1ULL: 
    cycle1_state = 1ULL;
    break;
  case 2ULL: 
    cycle1_state = 0ULL;
    break;
  }
}
// resource: mux_1bx2i1c
// resource: regr_en_1
void fir::drive_cycle2_state(){
  switch( (sc_uint<2>)((sc_uint<2> )(sc_bv<2>)((sc_bv<1>)(t_18.read()), 
          (sc_bv<1>)(t_15.read()))) ) {
  case 1ULL: 
    cycle2_state = 1ULL;
    break;
  case 2ULL: 
    cycle2_state = cycle1_state.read();
    break;
  }
}
// resource: regr_sc_1
void fir::drive_global_state(){
  if ( (rst.read() == 0ULL) ) {
    global_state = 0ULL;
  } else {
    global_state = 1ULL;
  }
}
void fir::drive_t_0(){
  t_0 = (sc_uint<1> )(( ~en_0.read() )) & (sc_uint<1> )(( ~cycle1_state.read() )
        ) & en_1.read() & global_state.read();
}
void fir::drive_t_1(){
  t_1 = en_0.read() & global_state.read();
}
void fir::drive_t_2(){
  t_2 = (sc_uint<1> )(( ~cycle1_state.read() )) & en_1.read() & global_state
        .read();
}
void fir::drive_t_3(){
  t_3 = !global_state.read() | cycle1_state.read() | !en_1.read();
}
void fir::drive_t_11(){
  t_11 = ~cycle1_state.read();
}
void fir::drive_t_13(){
  t_13 = ~cycle2_state.read();
}
void fir::drive_t_15(){
  t_15 = ~global_state.read();
}
void fir::drive_t_18(){
  t_18 = en_1.read() & global_state.read();
}
void fir::drive_din_busy(){
  din_busy = (sc_uint<1> ) (((/*imp*/sc_uint<1> ) fir_gen_busy_r_1_2_out1.read()
             .range(2,2)));
}
void fir::drive_din_m_data_is_valid(){
  din_m_data_is_valid = (sc_uint<1> ) (((/*imp*/sc_uint<1> ) 
                        fir_gen_busy_r_1_2_out1.read().range(1,1)));
}
// resource: fir_gen_busy_r_1  instance: fir_gen_busy_r_1_2
void fir::fir_gen_busy_r_1_2_p9(){
  fir_gen_busy_r_1_2_out1 = (sc_uint<3> ) (( (sc_biguint<3> )(sc_bv<3>)(
                            (sc_bv<1>)(fir_gen_busy_r_1_2_gnew_busy.read()), 
                            (sc_bv<2>)(( (sc_biguint<2> )(sc_bv<2>)((sc_bv<1>)(
                            fir_gen_busy_r_1_2_gdiv.read()), 
                            (sc_bv<1>)(fir_gen_busy_r_1_2_gen_busy_din_m_data_is_invalid_next
                            .read())) ))) ));
}
// resource: fir_gen_busy_r_1  instance: fir_gen_busy_r_1_2
void fir::fir_gen_busy_r_1_2_p8(){
  fir_gen_busy_r_1_2_gen_busy_din_m_data_is_invalid_next = ~(sc_uint<1>)fir_gen_busy_r_1_2_gdiv
                                                           .read();
}
// resource: fir_gen_busy_r_1  instance: fir_gen_busy_r_1_2
void fir::fir_gen_busy_r_1_2_p7(){
  fir_gen_busy_r_1_2_gdiv = (sc_uint<1> ) ((sc_uint<1> )din_vld.read() & !
                            fir_gen_busy_r_1_2_gnew_req.read() | (sc_uint<1> )
                            din_m_stall_reg_full.read());
}
// resource: fir_gen_busy_r_1  instance: fir_gen_busy_r_1_2
void fir::fir_gen_busy_r_1_2_p6(){
  fir_gen_busy_r_1_2_gnew_busy = (sc_uint<1> ) (fir_gen_busy_r_1_2_gnew_req
                                 .read() | (sc_uint<1> )din_m_stall_reg_full
                                 .read());
}
// resource: fir_gen_busy_r_1  instance: fir_gen_busy_r_1_2
void fir::fir_gen_busy_r_1_2_p5(){
  fir_gen_busy_r_1_2_gnew_req = (sc_uint<1> ) ((sc_uint<1> )din_m_busy_req_0
                                .read() & ( din_m_unvalidated_req.read() | 
                                din_vld.read() ));
}
// resource: regr_ss_1
void fir::drive_din_m_unvalidated_req(){
  if ( (rst.read() == 0ULL) ) {
    din_m_unvalidated_req = 1ULL;
  } else {
    din_m_unvalidated_req = (sc_uint<1> ) (fir_N_Muxb_1_2_8_4_1_out1.read());
  }
}
// resource: fir_N_Muxb_1_2_8_4
void fir::fir_N_Muxb_1_2_8_4_1(){
  if ( din_m_busy_req_0.read() ) {
    fir_N_Muxb_1_2_8_4_1_out1 = (sc_uint<1> ) (din_m_unvalidated_req.read());
  } else {
    fir_N_Muxb_1_2_8_4_1_out1 = (sc_uint<1> ) (din_vld.read());
  }
}
// resource: regr_en_8
void fir::drive_din_m_stall_reg(){
  switch( (sc_uint<1>)(fir_And_1Ux1U_1U_4_26_out1.read()) ) {
  case 1ULL: 
    din_m_stall_reg = din_data.read();
    break;
  case 0ULL: 
    break;
  }
}
// resource: fir_Not_1U_1U_4  instance: fir_Not_1U_1U_4_24
void fir::fir_Not_1U_1U_4_24(){
  fir_Not_1U_1U_4_24_out1 = !din_m_stall_reg_full.read();
}
// resource: fir_And_1Ux1U_1U_4  instance: fir_And_1Ux1U_1U_4_25
void fir::fir_And_1Ux1U_1U_4_25(){
  fir_And_1Ux1U_1U_4_25_out1 = din_m_data_is_valid.read() & din_m_stalling
                               .read();
}
// resource: fir_And_1Ux1U_1U_4  instance: fir_And_1Ux1U_1U_4_26
void fir::fir_And_1Ux1U_1U_4_26(){
  fir_And_1Ux1U_1U_4_26_out1 = fir_And_1Ux1U_1U_4_25_out1.read() & 
                               fir_Not_1U_1U_4_24_out1.read();
}
// resource: regr_sc_1
void fir::drive_din_m_stall_reg_full(){
  if ( (rst.read() == 0ULL) ) {
    din_m_stall_reg_full = 0ULL;
  } else {
    din_m_stall_reg_full = (sc_uint<1> ) (fir_And_1Ux1U_1U_4_27_out1.read());
  }
}
// resource: fir_And_1Ux1U_1U_4  instance: fir_And_1Ux1U_1U_4_27
void fir::fir_And_1Ux1U_1U_4_27(){
  fir_And_1Ux1U_1U_4_27_out1 = din_m_data_is_valid.read() & din_m_stalling
                               .read();
}
void fir::drive_dout_vld(){
  dout_vld = (sc_uint<1> ) (fir_Or_1Ux1U_1U_4_5_out1.read());
}
// resource: fir_Or_1Ux1U_1U_4  instance: fir_Or_1Ux1U_1U_4_5
void fir::fir_Or_1Ux1U_1U_4_5(){
  fir_Or_1Ux1U_1U_4_5_out1 = (sc_uint<1> ) (dout_m_unacked_req.read() | (
                             sc_uint<1>)fir_Xor_1Ux1U_1U_1_4_out1.read());
}
// resource: regr_sc_1
void fir::drive_dout_m_unacked_req(){
  if ( (rst.read() == 0ULL) ) {
    dout_m_unacked_req = 0ULL;
  } else {
    dout_m_unacked_req = (sc_uint<1> ) (fir_And_1Ux1U_1U_1_6_out1.read());
  }
}
// resource: fir_And_1Ux1U_1U_1  instance: fir_And_1Ux1U_1U_1_6
void fir::fir_And_1Ux1U_1U_1_6(){
  fir_And_1Ux1U_1U_1_6_out1 = dout_busy.read() & dout_vld.read();
}
// resource: fir_Xor_1Ux1U_1U_1  instance: fir_Xor_1Ux1U_1U_1_4
void fir::fir_Xor_1Ux1U_1U_1_4(){
  fir_Xor_1Ux1U_1U_1_4_out1 = (sc_uint<1> ) (dout_m_req_m_trig_req.read() ^ 
                              dout_m_req_m_prev_trig_req.read());
}
// resource: regr_sc_1
void fir::drive_dout_m_req_m_prev_trig_req(){
  if ( (rst.read() == 0ULL) ) {
    dout_m_req_m_prev_trig_req = 0ULL;
  } else {
    dout_m_req_m_prev_trig_req = dout_m_req_m_trig_req.read();
  }
}
// resource: fir_Not_1U_1U_1  instance: fir_Not_1U_1U_1_7
void fir::fir_Not_1U_1U_1_7(){
  fir_Not_1U_1U_1_7_out1 = !dout_m_req_m_trig_req.read();
}
void fir::drive_dout_data(){
  dout_data = (sc_uint<11> ) (dout_data_slice.read());
}
