`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Sep  7 2022 16:02:31 CEST (Sep  7 2022 14:02:31 UTC)

module fir_gen_busy_r_4(in1, in2, in3, in4, out1);
  input in1, in2, in3, in4;
  output [2:0] out1;
  wire in1, in2, in3, in4;
  wire [2:0] out1;
  wire n_0;
  INVX1 g24(.A (out1[0]), .Y (out1[1]));
  AOI21X1 g25(.A0 (in1), .A1 (n_0), .B0 (in4), .Y (out1[0]));
  NAND2BX1 g26(.AN (in4), .B (n_0), .Y (out1[2]));
  OAI21X1 g27(.A0 (in1), .A1 (in3), .B0 (in2), .Y (n_0));
endmodule


