`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Sep  6 2022 17:00:07 CEST (Sep  6 2022 15:00:07 UTC)

module fir_N_Mux_8_2_10_4_1(in3, in2, ctrl1, out1);
  input [7:0] in3, in2;
  input ctrl1;
  output [7:0] out1;
  wire [7:0] in3, in2;
  wire ctrl1;
  wire [7:0] out1;
  wire n_6;
  AO22D1BWP g81(.A1 (in3[1]), .A2 (n_6), .B1 (in2[1]), .B2 (ctrl1), .Z
       (out1[1]));
  AO22D1BWP g88(.A1 (in3[2]), .A2 (n_6), .B1 (in2[2]), .B2 (ctrl1), .Z
       (out1[2]));
  AO22D1BWP g83(.A1 (in3[7]), .A2 (n_6), .B1 (in2[7]), .B2 (ctrl1), .Z
       (out1[7]));
  AO22D1BWP g84(.A1 (in3[0]), .A2 (n_6), .B1 (in2[0]), .B2 (ctrl1), .Z
       (out1[0]));
  AO22D1BWP g82(.A1 (in3[4]), .A2 (n_6), .B1 (in2[4]), .B2 (ctrl1), .Z
       (out1[4]));
  AO22D1BWP g85(.A1 (in3[5]), .A2 (n_6), .B1 (in2[5]), .B2 (ctrl1), .Z
       (out1[5]));
  AO22D1BWP g86(.A1 (in3[6]), .A2 (n_6), .B1 (in2[6]), .B2 (ctrl1), .Z
       (out1[6]));
  AO22D1BWP g87(.A1 (in3[3]), .A2 (n_6), .B1 (in2[3]), .B2 (ctrl1), .Z
       (out1[3]));
  INVD1BWP g89(.I (ctrl1), .ZN (n_6));
endmodule


