`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Sep  7 2022 16:14:14 CEST (Sep  7 2022 14:14:14 UTC)

module fir_Equal_3Ux1U_1U_1(in2, in1, out1);
  input [2:0] in2;
  input in1;
  output out1;
  wire [2:0] in2;
  wire in1;
  wire out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  AOI21X2 g32(.A0 (n_4), .A1 (n_6), .B0 (n_5), .Y (out1));
  NAND2X2 g33(.A (n_1), .B (n_3), .Y (n_6));
  NAND2X2 g34(.A (n_2), .B (n_0), .Y (n_5));
  NAND2X2 g35(.A (in2[0]), .B (in1), .Y (n_4));
  CLKINVX2 g39(.A (in1), .Y (n_3));
  CLKINVX3 g36(.A (in2[2]), .Y (n_2));
  CLKINVX4 g38(.A (in2[0]), .Y (n_1));
  CLKINVX2 g37(.A (in2[1]), .Y (n_0));
endmodule


