`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Sep  6 2022 16:19:04 CEST (Sep  6 2022 14:19:04 UTC)

module fir_N_Muxb_1_2_8_1_0(in3, in2, ctrl1, out1);
  input in3, in2, ctrl1;
  output out1;
  wire in3, in2, ctrl1;
  wire out1;
  wire n_0, n_1;
  OAI21D1BWP g11(.A1 (n_0), .A2 (ctrl1), .B (n_1), .ZN (out1));
  ND2D8BWP g12(.A1 (in2), .A2 (ctrl1), .ZN (n_1));
  INVD1BWP g13(.I (in3), .ZN (n_0));
endmodule


