`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Sep  7 2022 16:12:04 CEST (Sep  7 2022 14:12:04 UTC)

module fir_N_Mux_8_8_12_1(in9, in8, in7, in6, in5, in4, in3, in2,
     ctrl1, out1);
  input [7:0] in9, in8, in7, in6, in5, in4, in3, in2;
  input [2:0] ctrl1;
  output [7:0] out1;
  wire [7:0] in9, in8, in7, in6, in5, in4, in3, in2;
  wire [2:0] ctrl1;
  wire [7:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_167, n_168;
  NAND2X1 g172(.A (n_88), .B (n_81), .Y (out1[5]));
  NAND2X1 g173(.A (n_77), .B (n_84), .Y (out1[6]));
  NAND2X1 g174(.A (n_79), .B (n_82), .Y (out1[7]));
  NAND2X1 g177(.A (n_80), .B (n_78), .Y (out1[4]));
  NAND2X1 g178(.A (n_86), .B (n_83), .Y (out1[1]));
  NAND2X1 g175(.A (n_85), .B (n_87), .Y (out1[2]));
  NAND2X1 g179(.A (n_76), .B (n_75), .Y (out1[3]));
  NAND2X1 g176(.A (n_90), .B (n_89), .Y (out1[0]));
  NOR2X1 g189(.A (n_39), .B (n_71), .Y (n_90));
  NOR2BX1 g188(.AN (n_46), .B (n_74), .Y (n_89));
  NOR2X1 g184(.A (n_48), .B (n_62), .Y (n_88));
  NOR2BX1 g182(.AN (n_41), .B (n_65), .Y (n_87));
  NOR2X1 g180(.A (n_45), .B (n_57), .Y (n_86));
  NOR2X1 g181(.A (n_47), .B (n_67), .Y (n_85));
  NOR2BX1 g190(.AN (n_40), .B (n_64), .Y (n_84));
  NOR2BX1 g185(.AN (n_51), .B (n_68), .Y (n_83));
  NOR2BX1 g193(.AN (n_54), .B (n_66), .Y (n_82));
  NOR2BX1 g183(.AN (n_38), .B (n_59), .Y (n_81));
  NOR2X1 g192(.A (n_50), .B (n_70), .Y (n_80));
  NOR2X1 g186(.A (n_44), .B (n_61), .Y (n_79));
  NOR2BX1 g191(.AN (n_43), .B (n_63), .Y (n_78));
  NOR2X1 g187(.A (n_55), .B (n_60), .Y (n_77));
  NOR2X1 g194(.A (n_42), .B (n_58), .Y (n_76));
  NOR2BX1 g195(.AN (n_56), .B (n_73), .Y (n_75));
  OAI2BB1X1 g215(.A0N (in4[0]), .A1N (n_72), .B0 (n_22), .Y (n_74));
  OAI2BB1X1 g212(.A0N (in4[3]), .A1N (n_72), .B0 (n_24), .Y (n_73));
  OAI2BB1X1 g213(.A0N (in7[0]), .A1N (n_69), .B0 (n_30), .Y (n_71));
  OAI2BB1X1 g214(.A0N (in7[4]), .A1N (n_69), .B0 (n_29), .Y (n_70));
  OAI2BB1X1 g208(.A0N (in4[1]), .A1N (n_72), .B0 (n_33), .Y (n_68));
  OAI2BB1X1 g200(.A0N (in7[2]), .A1N (n_69), .B0 (n_21), .Y (n_67));
  OAI2BB1X1 g217(.A0N (in4[7]), .A1N (n_72), .B0 (n_23), .Y (n_66));
  OAI2BB1X1 g201(.A0N (in4[2]), .A1N (n_72), .B0 (n_20), .Y (n_65));
  OAI2BB1X1 g223(.A0N (in4[6]), .A1N (n_72), .B0 (n_26), .Y (n_64));
  OAI2BB1X1 g219(.A0N (in4[4]), .A1N (n_72), .B0 (n_28), .Y (n_63));
  OAI2BB1X1 g203(.A0N (in7[5]), .A1N (n_69), .B0 (n_31), .Y (n_62));
  OAI2BB1X1 g222(.A0N (in7[7]), .A1N (n_69), .B0 (n_27), .Y (n_61));
  OAI2BB1X1 g218(.A0N (in7[6]), .A1N (n_69), .B0 (n_37), .Y (n_60));
  OAI2BB1X1 g204(.A0N (in4[5]), .A1N (n_72), .B0 (n_36), .Y (n_59));
  OAI2BB1X1 g225(.A0N (in7[3]), .A1N (n_69), .B0 (n_25), .Y (n_58));
  OAI2BB1X1 g206(.A0N (in7[1]), .A1N (n_69), .B0 (n_35), .Y (n_57));
  AOI22XL g211(.A0 (in2[3]), .A1 (n_53), .B0 (in3[3]), .B1 (n_52), .Y
       (n_56));
  OAI2BB1X1 g209(.A0N (in9[6]), .A1N (n_49), .B0 (n_12), .Y (n_55));
  AOI22XL g197(.A0 (in2[7]), .A1 (n_53), .B0 (in3[7]), .B1 (n_52), .Y
       (n_54));
  AOI22XL g210(.A0 (in2[1]), .A1 (n_53), .B0 (in3[1]), .B1 (n_52), .Y
       (n_51));
  OAI2BB1X1 g196(.A0N (in9[4]), .A1N (n_49), .B0 (n_15), .Y (n_50));
  OAI2BB1X1 g198(.A0N (in9[5]), .A1N (n_49), .B0 (n_11), .Y (n_48));
  OAI2BB1X1 g199(.A0N (in9[2]), .A1N (n_49), .B0 (n_18), .Y (n_47));
  AOI22XL g216(.A0 (in2[0]), .A1 (n_53), .B0 (in3[0]), .B1 (n_52), .Y
       (n_46));
  OAI2BB1X1 g205(.A0N (in9[1]), .A1N (n_49), .B0 (n_19), .Y (n_45));
  OAI2BB1X1 g220(.A0N (in9[7]), .A1N (n_49), .B0 (n_16), .Y (n_44));
  AOI22XL g221(.A0 (in2[4]), .A1 (n_53), .B0 (in3[4]), .B1 (n_52), .Y
       (n_43));
  OAI2BB1X1 g224(.A0N (in9[3]), .A1N (n_49), .B0 (n_14), .Y (n_42));
  AOI22XL g202(.A0 (in2[2]), .A1 (n_53), .B0 (in3[2]), .B1 (n_52), .Y
       (n_41));
  AOI22XL g226(.A0 (in2[6]), .A1 (n_53), .B0 (in3[6]), .B1 (n_52), .Y
       (n_40));
  OAI2BB1X1 g227(.A0N (in9[0]), .A1N (n_49), .B0 (n_13), .Y (n_39));
  AOI22XL g207(.A0 (in2[5]), .A1 (n_53), .B0 (in3[5]), .B1 (n_52), .Y
       (n_38));
  NAND2X1 g240(.A (in6[6]), .B (n_34), .Y (n_37));
  NAND2X1 g235(.A (in5[5]), .B (n_32), .Y (n_36));
  NAND2X1 g237(.A (in6[1]), .B (n_34), .Y (n_35));
  NAND2X1 g239(.A (in5[1]), .B (n_32), .Y (n_33));
  NAND2X1 g233(.A (in6[5]), .B (n_34), .Y (n_31));
  NAND2X1 g242(.A (in6[0]), .B (n_34), .Y (n_30));
  NAND2X1 g244(.A (in6[4]), .B (n_34), .Y (n_29));
  NAND2X1 g245(.A (in5[4]), .B (n_32), .Y (n_28));
  NAND2X1 g228(.A (in6[7]), .B (n_34), .Y (n_27));
  NAND2X1 g248(.A (in5[6]), .B (n_32), .Y (n_26));
  NAND2X1 g250(.A (in6[3]), .B (n_34), .Y (n_25));
  NAND2X1 g251(.A (in5[3]), .B (n_32), .Y (n_24));
  NAND2X1 g247(.A (in5[7]), .B (n_32), .Y (n_23));
  NAND2X1 g230(.A (in5[0]), .B (n_32), .Y (n_22));
  NAND2X1 g231(.A (in6[2]), .B (n_34), .Y (n_21));
  NAND2X1 g232(.A (in5[2]), .B (n_32), .Y (n_20));
  NAND2X1 g236(.A (in8[1]), .B (n_17), .Y (n_19));
  NAND2X1 g234(.A (in8[2]), .B (n_17), .Y (n_18));
  NAND2X1 g238(.A (in8[7]), .B (n_17), .Y (n_16));
  NAND2X1 g241(.A (in8[4]), .B (n_17), .Y (n_15));
  NAND2X1 g249(.A (in8[3]), .B (n_17), .Y (n_14));
  NAND2X1 g246(.A (in8[0]), .B (n_17), .Y (n_13));
  NAND2X1 g243(.A (in8[6]), .B (n_17), .Y (n_12));
  NAND2X1 g229(.A (in8[5]), .B (n_17), .Y (n_11));
  NOR2X4 g255(.A (n_10), .B (n_3), .Y (n_52));
  NOR2X2 g256(.A (ctrl1[0]), .B (n_5), .Y (n_72));
  NOR2X4 g257(.A (n_10), .B (n_8), .Y (n_32));
  NOR2X2 g258(.A (n_10), .B (n_7), .Y (n_69));
  NOR2X4 g259(.A (ctrl1[0]), .B (n_9), .Y (n_34));
  NOR2X2 g252(.A (n_10), .B (n_2), .Y (n_49));
  NOR2X4 g254(.A (ctrl1[0]), .B (n_0), .Y (n_17));
  NAND2X4 g267(.A (ctrl1[2]), .B (n_168), .Y (n_9));
  NAND2X4 g264(.A (ctrl1[1]), .B (n_4), .Y (n_8));
  NOR3X6 g253(.A (ctrl1[2]), .B (ctrl1[1]), .C (ctrl1[0]), .Y (n_53));
  NAND2X2 g265(.A (ctrl1[2]), .B (n_167), .Y (n_7));
  NAND2X4 g266(.A (ctrl1[1]), .B (n_4), .Y (n_5));
  CLKINVX3 g260(.A (n_1), .Y (n_3));
  NAND2X2 g261(.A (ctrl1[2]), .B (ctrl1[1]), .Y (n_2));
  NOR2X8 g262(.A (ctrl1[2]), .B (ctrl1[1]), .Y (n_1));
  NAND2X4 g263(.A (ctrl1[2]), .B (ctrl1[1]), .Y (n_0));
  CLKINVX3 g269(.A (ctrl1[0]), .Y (n_10));
  CLKINVX4 g268(.A (ctrl1[2]), .Y (n_4));
  CLKINVX4 fopt(.A (ctrl1[1]), .Y (n_167));
  CLKINVX4 fopt271(.A (ctrl1[1]), .Y (n_168));
endmodule


