`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Sep  7 2022 16:12:04 CEST (Sep  7 2022 14:12:04 UTC)

module fir_LessThan_3Ux3U_1U_1(in2, in1, out1);
  input [2:0] in2, in1;
  output out1;
  wire [2:0] in2, in1;
  wire out1;
  wire gt_21_21_n_0, gt_21_21_n_1, gt_21_21_n_2, gt_21_21_n_3,
       gt_21_21_n_4, gt_21_21_n_5, gt_21_21_n_6, gt_21_21_n_7;
  wire gt_21_21_n_8;
  AOI21X1 gt_21_21_g45(.A0 (gt_21_21_n_3), .A1 (gt_21_21_n_8), .B0
       (gt_21_21_n_6), .Y (out1));
  NAND2X1 gt_21_21_g46(.A (gt_21_21_n_0), .B (gt_21_21_n_7), .Y
       (gt_21_21_n_8));
  NAND2X1 gt_21_21_g47(.A (gt_21_21_n_5), .B (gt_21_21_n_4), .Y
       (gt_21_21_n_7));
  NOR2BX1 gt_21_21_g49(.AN (in2[2]), .B (in1[2]), .Y (gt_21_21_n_6));
  NAND2X2 gt_21_21_g50(.A (in1[1]), .B (gt_21_21_n_1), .Y
       (gt_21_21_n_5));
  NAND2X2 gt_21_21_g51(.A (in1[0]), .B (gt_21_21_n_2), .Y
       (gt_21_21_n_4));
  NAND2BX1 gt_21_21_g52(.AN (in2[2]), .B (in1[2]), .Y (gt_21_21_n_3));
  CLKINVX3 gt_21_21_g54(.A (in2[0]), .Y (gt_21_21_n_2));
  CLKINVX4 gt_21_21_g55(.A (in2[1]), .Y (gt_21_21_n_1));
  NAND2BX1 gt_21_21_g2(.AN (in1[1]), .B (in2[1]), .Y (gt_21_21_n_0));
endmodule


