`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Sep  7 2022 16:14:09 CEST (Sep  7 2022 14:14:09 UTC)

module fir_Equal_3Ux1U_1U_4(in2, in1, out1);
  input [2:0] in2;
  input in1;
  output out1;
  wire [2:0] in2;
  wire in1;
  wire out1;
  wire n_0;
  NOR3BX1 g27(.AN (n_0), .B (in2[1]), .C (in2[2]), .Y (out1));
  XNOR2X1 g28(.A (in2[0]), .B (in1), .Y (n_0));
endmodule


