`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Sep  7 2022 16:14:16 CEST (Sep  7 2022 14:14:16 UTC)

module fir_Equal_1U_12_1(in1, out1);
  input [2:0] in1;
  output out1;
  wire [2:0] in1;
  wire out1;
  wire n_0;
  NOR3X6 g16(.A (in1[0]), .B (in1[1]), .C (n_0), .Y (out1));
  CLKINVX4 g17(.A (in1[2]), .Y (n_0));
endmodule


