
// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Jul 20 2022 17:08:14 CEST (Jul 20 2022 15:08:14 UTC)

// Verification Directory fv/mux 

module mux(idata_0, ivalid_0, ivch_0, idata_1, ivalid_1, ivch_1,
     idata_2, ivalid_2, ivch_2, idata_3, ivalid_3, ivch_3, sel, odata,
     ovalid, ovch);
  input [28:0] idata_0, idata_1, idata_2, idata_3;
  input ivalid_0, ivalid_1, ivalid_2, ivalid_3;
  input [1:0] ivch_0, ivch_1, ivch_2, ivch_3;
  input [3:0] sel;
  output [28:0] odata;
  output ovalid;
  output [1:0] ovch;
  wire [28:0] idata_0, idata_1, idata_2, idata_3;
  wire ivalid_0, ivalid_1, ivalid_2, ivalid_3;
  wire [1:0] ivch_0, ivch_1, ivch_2, ivch_3;
  wire [3:0] sel;
  wire [28:0] odata;
  wire ovalid;
  wire [1:0] ovch;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_56, n_60, n_69;
  wire n_70;
  AO221D0BWP g1731__2398(.A1 (n_70), .A2 (idata_0[18]), .B1 (n_69), .B2
       (idata_1[18]), .C (n_28), .Z (odata[18]));
  AO221D0BWP g1721__5107(.A1 (n_70), .A2 (idata_0[27]), .B1 (n_69), .B2
       (idata_1[27]), .C (n_20), .Z (odata[27]));
  AO221D0BWP g1722__6260(.A1 (n_70), .A2 (idata_0[25]), .B1 (n_69), .B2
       (idata_1[25]), .C (n_31), .Z (odata[25]));
  AO221D0BWP g1727__4319(.A1 (n_70), .A2 (idata_0[24]), .B1 (n_69), .B2
       (idata_1[24]), .C (n_21), .Z (odata[24]));
  AO221D0BWP g1703__8428(.A1 (n_70), .A2 (idata_0[23]), .B1 (n_60), .B2
       (idata_3[23]), .C (n_19), .Z (odata[23]));
  AO221D0BWP g1718__5526(.A1 (n_70), .A2 (idata_0[21]), .B1 (n_69), .B2
       (idata_1[21]), .C (n_32), .Z (odata[21]));
  AO221D0BWP g1725__6783(.A1 (n_70), .A2 (idata_0[20]), .B1 (n_69), .B2
       (idata_1[20]), .C (n_36), .Z (odata[20]));
  AO221D0BWP g1728__3680(.A1 (n_70), .A2 (idata_0[19]), .B1 (n_69), .B2
       (idata_1[19]), .C (n_24), .Z (odata[19]));
  AO221D0BWP g1716__1617(.A1 (n_70), .A2 (idata_0[28]), .B1 (n_56), .B2
       (idata_2[28]), .C (n_34), .Z (odata[28]));
  AO221D0BWP g1720__2802(.A1 (n_70), .A2 (ivch_0[0]), .B1 (n_60), .B2
       (ivch_3[0]), .C (n_33), .Z (ovch[0]));
  AO221D0BWP g1723__1705(.A1 (n_70), .A2 (idata_0[12]), .B1 (n_69), .B2
       (idata_1[12]), .C (n_30), .Z (odata[12]));
  AO221D0BWP g1724__5122(.A1 (n_70), .A2 (idata_0[11]), .B1 (n_69), .B2
       (idata_1[11]), .C (n_29), .Z (odata[11]));
  AO221D0BWP g1726__8246(.A1 (n_70), .A2 (idata_0[10]), .B1 (n_56), .B2
       (idata_2[10]), .C (n_26), .Z (odata[10]));
  AO221D0BWP g1729__7098(.A1 (n_70), .A2 (idata_0[9]), .B1 (n_69), .B2
       (idata_1[9]), .C (n_25), .Z (odata[9]));
  AO221D0BWP g1730__6131(.A1 (n_70), .A2 (idata_0[8]), .B1 (n_69), .B2
       (idata_1[8]), .C (n_23), .Z (odata[8]));
  AO221D0BWP g1717__1881(.A1 (n_70), .A2 (idata_0[7]), .B1 (n_69), .B2
       (idata_1[7]), .C (n_27), .Z (odata[7]));
  AO221D0BWP g1732__5115(.A1 (n_70), .A2 (ivch_0[1]), .B1 (n_69), .B2
       (ivch_1[1]), .C (n_22), .Z (ovch[1]));
  AO221D0BWP g1719__7482(.A1 (n_70), .A2 (idata_0[13]), .B1 (n_60), .B2
       (idata_3[13]), .C (n_35), .Z (odata[13]));
  AO221D0BWP g1705__4733(.A1 (n_60), .A2 (idata_3[6]), .B1 (n_56), .B2
       (idata_2[6]), .C (n_6), .Z (odata[6]));
  AO221D0BWP g1713__6161(.A1 (n_60), .A2 (idata_3[22]), .B1 (n_56), .B2
       (idata_2[22]), .C (n_15), .Z (odata[22]));
  AO221D0BWP g1704__9315(.A1 (n_60), .A2 (idata_3[17]), .B1 (n_56), .B2
       (idata_2[17]), .C (n_10), .Z (odata[17]));
  AO221D0BWP g1708__9945(.A1 (n_60), .A2 (idata_3[16]), .B1 (n_56), .B2
       (idata_2[16]), .C (n_7), .Z (odata[16]));
  AO221D0BWP g1711__2883(.A1 (n_60), .A2 (idata_3[15]), .B1 (n_56), .B2
       (idata_2[15]), .C (n_5), .Z (odata[15]));
  AO221D0BWP g1714__2346(.A1 (n_60), .A2 (idata_3[14]), .B1 (n_56), .B2
       (idata_2[14]), .C (n_11), .Z (odata[14]));
  AO221D0BWP g1702__1666(.A1 (n_60), .A2 (idata_3[26]), .B1 (n_56), .B2
       (idata_2[26]), .C (n_8), .Z (odata[26]));
  AO221D0BWP g1701__7410(.A1 (n_60), .A2 (ivalid_3), .B1 (n_56), .B2
       (ivalid_2), .C (n_9), .Z (ovalid));
  AO221D0BWP g1709__6417(.A1 (n_60), .A2 (idata_3[3]), .B1 (n_56), .B2
       (idata_2[3]), .C (n_13), .Z (odata[3]));
  AO221D0BWP g1710__5477(.A1 (n_60), .A2 (idata_3[2]), .B1 (n_56), .B2
       (idata_2[2]), .C (n_12), .Z (odata[2]));
  AO221D0BWP g1706__2398(.A1 (n_60), .A2 (idata_3[5]), .B1 (n_56), .B2
       (idata_2[5]), .C (n_16), .Z (odata[5]));
  AO221D0BWP g1715__5107(.A1 (n_60), .A2 (idata_3[0]), .B1 (n_56), .B2
       (idata_2[0]), .C (n_18), .Z (odata[0]));
  AO221D0BWP g1712__6260(.A1 (n_60), .A2 (idata_3[1]), .B1 (n_56), .B2
       (idata_2[1]), .C (n_14), .Z (odata[1]));
  AO221D0BWP g1707__4319(.A1 (n_60), .A2 (idata_3[4]), .B1 (n_56), .B2
       (idata_2[4]), .C (n_17), .Z (odata[4]));
  AO22D0BWP g1756__8428(.A1 (n_60), .A2 (idata_3[20]), .B1
       (idata_2[20]), .B2 (n_56), .Z (n_36));
  AO22D0BWP g1750__5526(.A1 (n_69), .A2 (idata_1[13]), .B1
       (idata_2[13]), .B2 (n_56), .Z (n_35));
  AO22D0BWP g1735__6783(.A1 (n_69), .A2 (idata_1[28]), .B1
       (idata_3[28]), .B2 (n_60), .Z (n_34));
  AO22D0BWP g1733__3680(.A1 (n_69), .A2 (ivch_1[0]), .B1 (ivch_2[0]),
       .B2 (n_56), .Z (n_33));
  AO22D0BWP g1752__1617(.A1 (n_60), .A2 (idata_3[21]), .B1
       (idata_2[21]), .B2 (n_56), .Z (n_32));
  AO22D0BWP g1753__2802(.A1 (n_60), .A2 (idata_3[25]), .B1
       (idata_2[25]), .B2 (n_56), .Z (n_31));
  AO22D0BWP g1754__1705(.A1 (n_60), .A2 (idata_3[12]), .B1
       (idata_2[12]), .B2 (n_56), .Z (n_30));
  AO22D0BWP g1755__5122(.A1 (n_60), .A2 (idata_3[11]), .B1
       (idata_2[11]), .B2 (n_56), .Z (n_29));
  AO22D0BWP g1749__8246(.A1 (n_60), .A2 (idata_3[18]), .B1
       (idata_2[18]), .B2 (n_56), .Z (n_28));
  AO22D0BWP g1763__7098(.A1 (n_60), .A2 (idata_3[7]), .B1 (idata_2[7]),
       .B2 (n_56), .Z (n_27));
  AO22D0BWP g1757__6131(.A1 (n_69), .A2 (idata_1[10]), .B1
       (idata_3[10]), .B2 (n_60), .Z (n_26));
  AO22D0BWP g1758__1881(.A1 (n_60), .A2 (idata_3[9]), .B1 (idata_2[9]),
       .B2 (n_56), .Z (n_25));
  AO22D0BWP g1759__5115(.A1 (n_60), .A2 (idata_3[19]), .B1
       (idata_2[19]), .B2 (n_56), .Z (n_24));
  AO22D0BWP g1760__7482(.A1 (n_60), .A2 (idata_3[8]), .B1 (idata_2[8]),
       .B2 (n_56), .Z (n_23));
  AO22D0BWP g1747__4733(.A1 (n_60), .A2 (ivch_3[1]), .B1 (ivch_2[1]),
       .B2 (n_56), .Z (n_22));
  AO22D0BWP g1761__6161(.A1 (n_60), .A2 (idata_3[24]), .B1
       (idata_2[24]), .B2 (n_56), .Z (n_21));
  AO22D0BWP g1762__9315(.A1 (n_60), .A2 (idata_3[27]), .B1
       (idata_2[27]), .B2 (n_56), .Z (n_20));
  AO22D0BWP g1739__9945(.A1 (n_69), .A2 (idata_1[23]), .B1
       (idata_2[23]), .B2 (n_56), .Z (n_19));
  AO22D0BWP g1743__2883(.A1 (n_70), .A2 (idata_0[0]), .B1 (idata_1[0]),
       .B2 (n_69), .Z (n_18));
  AO22D0BWP g1737__2346(.A1 (n_70), .A2 (idata_0[4]), .B1 (idata_1[4]),
       .B2 (n_69), .Z (n_17));
  AO22D0BWP g1734__1666(.A1 (n_70), .A2 (idata_0[5]), .B1 (idata_1[5]),
       .B2 (n_69), .Z (n_16));
  AO22D0BWP g1751__7410(.A1 (n_70), .A2 (idata_0[22]), .B1
       (idata_1[22]), .B2 (n_69), .Z (n_15));
  AO22D0BWP g1742__6417(.A1 (n_70), .A2 (idata_0[1]), .B1 (idata_1[1]),
       .B2 (n_69), .Z (n_14));
  AO22D0BWP g1738__5477(.A1 (n_70), .A2 (idata_0[3]), .B1 (idata_1[3]),
       .B2 (n_69), .Z (n_13));
  AO22D0BWP g1741__2398(.A1 (n_70), .A2 (idata_0[2]), .B1 (idata_1[2]),
       .B2 (n_69), .Z (n_12));
  AO22D0BWP g1764__5107(.A1 (n_70), .A2 (idata_0[14]), .B1
       (idata_1[14]), .B2 (n_69), .Z (n_11));
  AO22D0BWP g1736__6260(.A1 (n_70), .A2 (idata_0[17]), .B1
       (idata_1[17]), .B2 (n_69), .Z (n_10));
  AO22D0BWP g1745__4319(.A1 (n_70), .A2 (ivalid_0), .B1 (ivalid_1), .B2
       (n_69), .Z (n_9));
  AO22D0BWP g1746__8428(.A1 (n_70), .A2 (idata_0[26]), .B1
       (idata_1[26]), .B2 (n_69), .Z (n_8));
  AO22D0BWP g1740__5526(.A1 (n_70), .A2 (idata_0[16]), .B1
       (idata_1[16]), .B2 (n_69), .Z (n_7));
  AO22D0BWP g1748__6783(.A1 (n_70), .A2 (idata_0[6]), .B1 (idata_1[6]),
       .B2 (n_69), .Z (n_6));
  AO22D0BWP g1744__3680(.A1 (n_70), .A2 (idata_0[15]), .B1
       (idata_1[15]), .B2 (n_69), .Z (n_5));
  CKAN2D2BWP g1765__1617(.A1 (n_2), .A2 (n_4), .Z (n_60));
  CKAN2D2BWP g1766__2802(.A1 (n_1), .A2 (n_4), .Z (n_56));
  AN3D2BWP g1767__1705(.A1 (n_3), .A2 (n_4), .A3 (sel[1]), .Z (n_69));
  AN3D2BWP g1768__5122(.A1 (n_3), .A2 (n_0), .A3 (sel[0]), .Z (n_70));
  INR3D0BWP g1770__8246(.A1 (sel[3]), .B1 (sel[2]), .B2 (sel[1]), .ZN
       (n_2));
  INR3D0BWP g1769__7098(.A1 (sel[2]), .B1 (sel[3]), .B2 (sel[1]), .ZN
       (n_1));
  NR2D0BWP g1771__6131(.A1 (sel[3]), .A2 (sel[2]), .ZN (n_3));
  CKND0BWP g1773(.I (sel[0]), .ZN (n_4));
  CKND0BWP g1772(.I (sel[1]), .ZN (n_0));
endmodule

