
// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Jul 21 2022 21:40:39 CEST (Jul 21 2022 19:40:39 UTC)

// Verification Directory fv/mux 

module mux(idata_0, ivalid_0, ivch_0, idata_1, ivalid_1, ivch_1, sel,
     odata, ovalid, ovch);
  input [11:0] idata_0, idata_1;
  input ivalid_0, ivalid_1;
  input [1:0] ivch_0, ivch_1, sel;
  output [11:0] odata;
  output ovalid;
  output [1:0] ovch;
  wire [11:0] idata_0, idata_1;
  wire ivalid_0, ivalid_1;
  wire [1:0] ivch_0, ivch_1, sel;
  wire [11:0] odata;
  wire ovalid;
  wire [1:0] ovch;
  wire n_13, n_14;
  AO22D0BWP g396__2398(.A1 (n_14), .A2 (idata_1[10]), .B1
       (idata_0[10]), .B2 (n_13), .Z (odata[10]));
  AO22D0BWP g407__5107(.A1 (n_14), .A2 (idata_1[1]), .B1 (idata_0[1]),
       .B2 (n_13), .Z (odata[1]));
  AO22D0BWP g409__6260(.A1 (n_14), .A2 (idata_1[0]), .B1 (idata_0[0]),
       .B2 (n_13), .Z (odata[0]));
  AO22D0BWP g398__4319(.A1 (n_14), .A2 (ivalid_1), .B1 (ivalid_0), .B2
       (n_13), .Z (ovalid));
  AO22D0BWP g399__8428(.A1 (n_14), .A2 (ivch_1[1]), .B1 (ivch_0[1]),
       .B2 (n_13), .Z (ovch[1]));
  AO22D0BWP g400__5526(.A1 (n_14), .A2 (ivch_1[0]), .B1 (ivch_0[0]),
       .B2 (n_13), .Z (ovch[0]));
  AO22D0BWP g401__6783(.A1 (n_14), .A2 (idata_1[11]), .B1
       (idata_0[11]), .B2 (n_13), .Z (odata[11]));
  AO22D0BWP g397__3680(.A1 (n_14), .A2 (idata_1[5]), .B1 (idata_0[5]),
       .B2 (n_13), .Z (odata[5]));
  AO22D0BWP g395__1617(.A1 (n_14), .A2 (idata_1[8]), .B1 (idata_0[8]),
       .B2 (n_13), .Z (odata[8]));
  AO22D0BWP g405__2802(.A1 (n_14), .A2 (idata_1[7]), .B1 (idata_0[7]),
       .B2 (n_13), .Z (odata[7]));
  AO22D0BWP g408__1705(.A1 (n_14), .A2 (idata_1[6]), .B1 (idata_0[6]),
       .B2 (n_13), .Z (odata[6]));
  AO22D0BWP g404__5122(.A1 (n_14), .A2 (idata_1[9]), .B1 (idata_0[9]),
       .B2 (n_13), .Z (odata[9]));
  AO22D0BWP g406__8246(.A1 (n_14), .A2 (idata_1[4]), .B1 (idata_0[4]),
       .B2 (n_13), .Z (odata[4]));
  AO22D0BWP g403__7098(.A1 (n_14), .A2 (idata_1[3]), .B1 (idata_0[3]),
       .B2 (n_13), .Z (odata[3]));
  AO22D0BWP g402__6131(.A1 (n_14), .A2 (idata_1[2]), .B1 (idata_0[2]),
       .B2 (n_13), .Z (odata[2]));
  INR2XD1BWP g411__1881(.A1 (sel[1]), .B1 (sel[0]), .ZN (n_14));
  INR2XD1BWP g410__5115(.A1 (sel[0]), .B1 (sel[1]), .ZN (n_13));
endmodule

