
// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Jul 20 2022 12:17:09 CEST (Jul 20 2022 10:17:09 UTC)

// Verification Directory fv/mux 

module mux(idata_0, ivalid_0, ivch_0, idata_1, ivalid_1, ivch_1,
     idata_2, ivalid_2, ivch_2, sel, odata, ovalid, ovch);
  input [21:0] idata_0, idata_1, idata_2;
  input ivalid_0, ivalid_1, ivalid_2;
  input [1:0] ivch_0, ivch_1, ivch_2;
  input [2:0] sel;
  output [21:0] odata;
  output ovalid;
  output [1:0] ovch;
  wire [21:0] idata_0, idata_1, idata_2;
  wire ivalid_0, ivalid_1, ivalid_2;
  wire [1:0] ivch_0, ivch_1, ivch_2;
  wire [2:0] sel;
  wire [21:0] odata;
  wire ovalid;
  wire [1:0] ovch;
  wire n_0, n_1, n_2, n_26, n_27, n_28;
  AO222D0BWP g1069__2398(.A1 (n_27), .A2 (idata_0[14]), .B1 (n_26), .B2
       (idata_1[14]), .C1 (n_28), .C2 (idata_2[14]), .Z (odata[14]));
  AO222D0BWP g1082__5107(.A1 (n_28), .A2 (idata_2[19]), .B1 (n_27), .B2
       (idata_0[19]), .C1 (n_26), .C2 (idata_1[19]), .Z (odata[19]));
  AO222D0BWP g1068__6260(.A1 (n_28), .A2 (idata_2[18]), .B1 (n_27), .B2
       (idata_0[18]), .C1 (n_26), .C2 (idata_1[18]), .Z (odata[18]));
  AO222D0BWP g1075__4319(.A1 (n_27), .A2 (idata_0[17]), .B1 (n_28), .B2
       (idata_2[17]), .C1 (n_26), .C2 (idata_1[17]), .Z (odata[17]));
  AO222D0BWP g1083__8428(.A1 (n_27), .A2 (idata_0[16]), .B1 (n_28), .B2
       (idata_2[16]), .C1 (n_26), .C2 (idata_1[16]), .Z (odata[16]));
  AO222D0BWP g1088__5526(.A1 (n_28), .A2 (idata_2[15]), .B1 (n_27), .B2
       (idata_0[15]), .C1 (n_26), .C2 (idata_1[15]), .Z (odata[15]));
  AO222D0BWP g1072__6783(.A1 (n_27), .A2 (idata_0[21]), .B1 (n_28), .B2
       (idata_2[21]), .C1 (n_26), .C2 (idata_1[21]), .Z (odata[21]));
  AO222D0BWP g1066__3680(.A1 (n_28), .A2 (idata_2[13]), .B1 (n_27), .B2
       (idata_0[13]), .C1 (n_26), .C2 (idata_1[13]), .Z (odata[13]));
  AO222D0BWP g1076__1617(.A1 (n_27), .A2 (idata_0[12]), .B1 (n_26), .B2
       (idata_1[12]), .C1 (n_28), .C2 (idata_2[12]), .Z (odata[12]));
  AO222D0BWP g1079__2802(.A1 (n_28), .A2 (idata_2[11]), .B1 (n_27), .B2
       (idata_0[11]), .C1 (n_26), .C2 (idata_1[11]), .Z (odata[11]));
  AO222D0BWP g1084__1705(.A1 (n_27), .A2 (idata_0[10]), .B1 (n_28), .B2
       (idata_2[10]), .C1 (n_26), .C2 (idata_1[10]), .Z (odata[10]));
  AO222D0BWP g1087__5122(.A1 (n_28), .A2 (idata_2[9]), .B1 (n_27), .B2
       (idata_0[9]), .C1 (n_26), .C2 (idata_1[9]), .Z (odata[9]));
  AO222D0BWP g1089__8246(.A1 (n_27), .A2 (idata_0[8]), .B1 (n_28), .B2
       (idata_2[8]), .C1 (n_26), .C2 (idata_1[8]), .Z (odata[8]));
  AO222D0BWP g1090__7098(.A1 (n_27), .A2 (idata_0[7]), .B1 (n_28), .B2
       (idata_2[7]), .C1 (n_26), .C2 (idata_1[7]), .Z (odata[7]));
  AO222D0BWP g1070__6131(.A1 (n_27), .A2 (idata_0[6]), .B1 (n_26), .B2
       (idata_1[6]), .C1 (n_28), .C2 (idata_2[6]), .Z (odata[6]));
  AO222D0BWP g1071__1881(.A1 (n_27), .A2 (idata_0[5]), .B1 (n_28), .B2
       (idata_2[5]), .C1 (n_26), .C2 (idata_1[5]), .Z (odata[5]));
  AO222D0BWP g1073__5115(.A1 (n_28), .A2 (idata_2[4]), .B1 (n_27), .B2
       (idata_0[4]), .C1 (n_26), .C2 (idata_1[4]), .Z (odata[4]));
  AO222D0BWP g1074__7482(.A1 (n_28), .A2 (idata_2[3]), .B1 (n_27), .B2
       (idata_0[3]), .C1 (n_26), .C2 (idata_1[3]), .Z (odata[3]));
  AO222D0BWP g1077__4733(.A1 (n_27), .A2 (idata_0[2]), .B1 (n_28), .B2
       (idata_2[2]), .C1 (n_26), .C2 (idata_1[2]), .Z (odata[2]));
  AO222D0BWP g1078__6161(.A1 (n_27), .A2 (idata_0[1]), .B1 (n_28), .B2
       (idata_2[1]), .C1 (n_26), .C2 (idata_1[1]), .Z (odata[1]));
  AO222D0BWP g1080__9315(.A1 (n_27), .A2 (idata_0[0]), .B1 (n_28), .B2
       (idata_2[0]), .C1 (n_26), .C2 (idata_1[0]), .Z (odata[0]));
  AO222D0BWP g1081__9945(.A1 (n_28), .A2 (ivalid_2), .B1 (n_27), .B2
       (ivalid_0), .C1 (n_26), .C2 (ivalid_1), .Z (ovalid));
  AO222D0BWP g1085__2883(.A1 (n_27), .A2 (ivch_0[1]), .B1 (n_26), .B2
       (ivch_1[1]), .C1 (n_28), .C2 (ivch_2[1]), .Z (ovch[1]));
  AO222D0BWP g1086__2346(.A1 (n_27), .A2 (ivch_0[0]), .B1 (n_26), .B2
       (ivch_1[0]), .C1 (n_28), .C2 (ivch_2[0]), .Z (ovch[0]));
  AO222D0BWP g1067__1666(.A1 (n_28), .A2 (idata_2[20]), .B1 (n_27), .B2
       (idata_0[20]), .C1 (n_26), .C2 (idata_1[20]), .Z (odata[20]));
  CKAN2D1BWP g1091__7410(.A1 (n_2), .A2 (sel[0]), .Z (n_27));
  NR2D3BWP g1093__6417(.A1 (n_1), .A2 (sel[0]), .ZN (n_26));
  NR2D3BWP g1092__5477(.A1 (n_0), .A2 (sel[0]), .ZN (n_28));
  NR2D0BWP g1094__2398(.A1 (sel[2]), .A2 (sel[1]), .ZN (n_2));
  IND2D0BWP g1096__5107(.A1 (sel[2]), .B1 (sel[1]), .ZN (n_1));
  IND2D0BWP g1095__6260(.A1 (sel[1]), .B1 (sel[2]), .ZN (n_0));
endmodule

