
// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Jul 22 2022 00:23:49 CEST (Jul 21 2022 22:23:49 UTC)

// Verification Directory fv/mux 

module mux(idata_0, ivalid_0, ivch_0, idata_1, ivalid_1, ivch_1, sel,
     odata, ovalid, ovch);
  input [66:0] idata_0, idata_1;
  input ivalid_0, ivalid_1;
  input [1:0] ivch_0, ivch_1, sel;
  output [66:0] odata;
  output ovalid;
  output [1:0] ovch;
  wire [66:0] idata_0, idata_1;
  wire ivalid_0, ivalid_1;
  wire [1:0] ivch_0, ivch_1, sel;
  wire [66:0] odata;
  wire ovalid;
  wire [1:0] ovch;
  wire n_0, n_1, n_70, n_71;
  AO22D0BWP g1716__2398(.A1 (n_71), .A2 (idata_1[6]), .B1 (idata_0[6]),
       .B2 (n_70), .Z (odata[6]));
  AO22D0BWP g1706__5107(.A1 (n_71), .A2 (idata_1[39]), .B1
       (idata_0[39]), .B2 (n_70), .Z (odata[39]));
  AO22D0BWP g1710__6260(.A1 (n_71), .A2 (idata_1[38]), .B1
       (idata_0[38]), .B2 (n_70), .Z (odata[38]));
  AO22D0BWP g1713__4319(.A1 (n_71), .A2 (idata_1[37]), .B1
       (idata_0[37]), .B2 (n_70), .Z (odata[37]));
  AO22D0BWP g1715__8428(.A1 (n_71), .A2 (idata_1[36]), .B1
       (idata_0[36]), .B2 (n_70), .Z (odata[36]));
  AO22D0BWP g1722__5526(.A1 (n_71), .A2 (idata_1[35]), .B1
       (idata_0[35]), .B2 (n_70), .Z (odata[35]));
  AO22D0BWP g1725__6783(.A1 (n_71), .A2 (idata_1[34]), .B1
       (idata_0[34]), .B2 (n_70), .Z (odata[34]));
  AO22D0BWP g1695__3680(.A1 (n_71), .A2 (idata_1[33]), .B1
       (idata_0[33]), .B2 (n_70), .Z (odata[33]));
  AO22D0BWP g1731__1617(.A1 (n_71), .A2 (idata_1[32]), .B1
       (idata_0[32]), .B2 (n_70), .Z (odata[32]));
  AO22D0BWP g1736__2802(.A1 (n_71), .A2 (idata_1[31]), .B1
       (idata_0[31]), .B2 (n_70), .Z (odata[31]));
  AO22D0BWP g1738__1705(.A1 (n_71), .A2 (idata_1[30]), .B1
       (idata_0[30]), .B2 (n_70), .Z (odata[30]));
  AO22D0BWP g1739__5122(.A1 (n_71), .A2 (idata_1[29]), .B1
       (idata_0[29]), .B2 (n_70), .Z (odata[29]));
  AO22D0BWP g1743__8246(.A1 (n_71), .A2 (idata_1[28]), .B1
       (idata_0[28]), .B2 (n_70), .Z (odata[28]));
  AO22D0BWP g1745__7098(.A1 (n_71), .A2 (idata_1[27]), .B1
       (idata_0[27]), .B2 (n_70), .Z (odata[27]));
  AO22D0BWP g1746__6131(.A1 (n_71), .A2 (idata_1[26]), .B1
       (idata_0[26]), .B2 (n_70), .Z (odata[26]));
  AO22D0BWP g1749__1881(.A1 (n_71), .A2 (idata_1[25]), .B1
       (idata_0[25]), .B2 (n_70), .Z (odata[25]));
  AO22D0BWP g1750__5115(.A1 (n_71), .A2 (idata_1[24]), .B1
       (idata_0[24]), .B2 (n_70), .Z (odata[24]));
  AO22D0BWP g1752__7482(.A1 (n_71), .A2 (idata_1[23]), .B1
       (idata_0[23]), .B2 (n_70), .Z (odata[23]));
  AO22D0BWP g1755__4733(.A1 (n_71), .A2 (idata_1[22]), .B1
       (idata_0[22]), .B2 (n_70), .Z (odata[22]));
  AO22D0BWP g1756__6161(.A1 (n_71), .A2 (idata_1[21]), .B1
       (idata_0[21]), .B2 (n_70), .Z (odata[21]));
  AO22D0BWP g1757__9315(.A1 (n_71), .A2 (idata_1[20]), .B1
       (idata_0[20]), .B2 (n_70), .Z (odata[20]));
  AO22D0BWP g1760__9945(.A1 (n_71), .A2 (idata_1[19]), .B1
       (idata_0[19]), .B2 (n_70), .Z (odata[19]));
  AO22D0BWP g1761__2883(.A1 (n_71), .A2 (idata_1[18]), .B1
       (idata_0[18]), .B2 (n_70), .Z (odata[18]));
  AO22D0BWP g1763__2346(.A1 (n_71), .A2 (idata_1[17]), .B1
       (idata_0[17]), .B2 (n_70), .Z (odata[17]));
  AO22D0BWP g1730__1666(.A1 (n_71), .A2 (idata_1[16]), .B1
       (idata_0[16]), .B2 (n_70), .Z (odata[16]));
  AO22D0BWP g1700__7410(.A1 (n_71), .A2 (idata_1[15]), .B1
       (idata_0[15]), .B2 (n_70), .Z (odata[15]));
  AO22D0BWP g1702__6417(.A1 (n_71), .A2 (idata_1[14]), .B1
       (idata_0[14]), .B2 (n_70), .Z (odata[14]));
  AO22D0BWP g1703__5477(.A1 (n_71), .A2 (idata_1[13]), .B1
       (idata_0[13]), .B2 (n_70), .Z (odata[13]));
  AO22D0BWP g1705__2398(.A1 (n_71), .A2 (idata_1[12]), .B1
       (idata_0[12]), .B2 (n_70), .Z (odata[12]));
  AO22D0BWP g1707__5107(.A1 (n_71), .A2 (idata_1[11]), .B1
       (idata_0[11]), .B2 (n_70), .Z (odata[11]));
  AO22D0BWP g1708__6260(.A1 (n_71), .A2 (idata_1[10]), .B1
       (idata_0[10]), .B2 (n_70), .Z (odata[10]));
  AO22D0BWP g1711__4319(.A1 (n_71), .A2 (idata_1[9]), .B1 (idata_0[9]),
       .B2 (n_70), .Z (odata[9]));
  AO22D0BWP g1712__8428(.A1 (n_71), .A2 (idata_1[8]), .B1 (idata_0[8]),
       .B2 (n_70), .Z (odata[8]));
  AO22D0BWP g1714__5526(.A1 (n_71), .A2 (idata_1[7]), .B1 (idata_0[7]),
       .B2 (n_70), .Z (odata[7]));
  AO22D0BWP g1729__6783(.A1 (n_71), .A2 (idata_1[66]), .B1
       (idata_0[66]), .B2 (n_70), .Z (odata[66]));
  AO22D0BWP g1701__3680(.A1 (n_71), .A2 (idata_1[40]), .B1
       (idata_0[40]), .B2 (n_70), .Z (odata[40]));
  AO22D0BWP g1718__1617(.A1 (n_71), .A2 (idata_1[4]), .B1 (idata_0[4]),
       .B2 (n_70), .Z (odata[4]));
  AO22D0BWP g1723__2802(.A1 (n_71), .A2 (idata_1[3]), .B1 (idata_0[3]),
       .B2 (n_70), .Z (odata[3]));
  AO22D0BWP g1724__1705(.A1 (n_71), .A2 (idata_1[2]), .B1 (idata_0[2]),
       .B2 (n_70), .Z (odata[2]));
  AO22D0BWP g1726__5122(.A1 (n_71), .A2 (idata_1[1]), .B1 (idata_0[1]),
       .B2 (n_70), .Z (odata[1]));
  AO22D0BWP g1727__8246(.A1 (n_71), .A2 (idata_1[0]), .B1 (idata_0[0]),
       .B2 (n_70), .Z (odata[0]));
  AO22D0BWP g1764__7098(.A1 (n_71), .A2 (ivalid_1), .B1 (ivalid_0), .B2
       (n_70), .Z (ovalid));
  AO22D0BWP g1732__6131(.A1 (n_71), .A2 (ivch_1[1]), .B1 (ivch_0[1]),
       .B2 (n_70), .Z (ovch[1]));
  AO22D0BWP g1733__1881(.A1 (n_71), .A2 (ivch_1[0]), .B1 (ivch_0[0]),
       .B2 (n_70), .Z (ovch[0]));
  AO22D0BWP g1696__5115(.A1 (n_71), .A2 (idata_1[65]), .B1
       (idata_0[65]), .B2 (n_70), .Z (odata[65]));
  AO22D0BWP g1740__7482(.A1 (n_71), .A2 (idata_1[64]), .B1
       (idata_0[64]), .B2 (n_70), .Z (odata[64]));
  AO22D0BWP g1719__4733(.A1 (n_71), .A2 (idata_1[63]), .B1
       (idata_0[63]), .B2 (n_70), .Z (odata[63]));
  AO22D0BWP g1741__6161(.A1 (n_71), .A2 (idata_1[62]), .B1
       (idata_0[62]), .B2 (n_70), .Z (odata[62]));
  AO22D0BWP g1753__9315(.A1 (n_71), .A2 (idata_1[61]), .B1
       (idata_0[61]), .B2 (n_70), .Z (odata[61]));
  AO22D0BWP g1697__9945(.A1 (n_71), .A2 (idata_1[60]), .B1
       (idata_0[60]), .B2 (n_70), .Z (odata[60]));
  AO22D0BWP g1720__2883(.A1 (n_71), .A2 (idata_1[59]), .B1
       (idata_0[59]), .B2 (n_70), .Z (odata[59]));
  AO22D0BWP g1734__2346(.A1 (n_71), .A2 (idata_1[58]), .B1
       (idata_0[58]), .B2 (n_70), .Z (odata[58]));
  AO22D0BWP g1742__1666(.A1 (n_71), .A2 (idata_1[57]), .B1
       (idata_0[57]), .B2 (n_70), .Z (odata[57]));
  AO22D0BWP g1747__7410(.A1 (n_71), .A2 (idata_1[56]), .B1
       (idata_0[56]), .B2 (n_70), .Z (odata[56]));
  AO22D0BWP g1758__6417(.A1 (n_71), .A2 (idata_1[55]), .B1
       (idata_0[55]), .B2 (n_70), .Z (odata[55]));
  AO22D0BWP g1698__5477(.A1 (n_71), .A2 (idata_1[54]), .B1
       (idata_0[54]), .B2 (n_70), .Z (odata[54]));
  AO22D0BWP g1704__2398(.A1 (n_71), .A2 (idata_1[53]), .B1
       (idata_0[53]), .B2 (n_70), .Z (odata[53]));
  AO22D0BWP g1709__5107(.A1 (n_71), .A2 (idata_1[52]), .B1
       (idata_0[52]), .B2 (n_70), .Z (odata[52]));
  AO22D0BWP g1721__6260(.A1 (n_71), .A2 (idata_1[51]), .B1
       (idata_0[51]), .B2 (n_70), .Z (odata[51]));
  AO22D0BWP g1728__4319(.A1 (n_71), .A2 (idata_1[50]), .B1
       (idata_0[50]), .B2 (n_70), .Z (odata[50]));
  AO22D0BWP g1735__8428(.A1 (n_71), .A2 (idata_1[49]), .B1
       (idata_0[49]), .B2 (n_70), .Z (odata[49]));
  AO22D0BWP g1737__5526(.A1 (n_71), .A2 (idata_1[48]), .B1
       (idata_0[48]), .B2 (n_70), .Z (odata[48]));
  AO22D0BWP g1744__6783(.A1 (n_71), .A2 (idata_1[47]), .B1
       (idata_0[47]), .B2 (n_70), .Z (odata[47]));
  AO22D0BWP g1748__3680(.A1 (n_71), .A2 (idata_1[46]), .B1
       (idata_0[46]), .B2 (n_70), .Z (odata[46]));
  AO22D0BWP g1751__1617(.A1 (n_71), .A2 (idata_1[45]), .B1
       (idata_0[45]), .B2 (n_70), .Z (odata[45]));
  AO22D0BWP g1754__2802(.A1 (n_71), .A2 (idata_1[44]), .B1
       (idata_0[44]), .B2 (n_70), .Z (odata[44]));
  AO22D0BWP g1759__1705(.A1 (n_71), .A2 (idata_1[43]), .B1
       (idata_0[43]), .B2 (n_70), .Z (odata[43]));
  AO22D0BWP g1762__5122(.A1 (n_71), .A2 (idata_1[42]), .B1
       (idata_0[42]), .B2 (n_70), .Z (odata[42]));
  AO22D0BWP g1699__8246(.A1 (n_71), .A2 (idata_1[41]), .B1
       (idata_0[41]), .B2 (n_70), .Z (odata[41]));
  AO22D0BWP g1717__7098(.A1 (n_71), .A2 (idata_1[5]), .B1 (idata_0[5]),
       .B2 (n_70), .Z (odata[5]));
  CKAN2D4BWP g1766__6131(.A1 (n_1), .A2 (sel[1]), .Z (n_71));
  CKAN2D4BWP g1765__1881(.A1 (n_0), .A2 (sel[0]), .Z (n_70));
  CKND0BWP g1767(.I (sel[0]), .ZN (n_1));
  CKND0BWP g1768(.I (sel[1]), .ZN (n_0));
endmodule

