
// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Jul 21 2022 21:54:45 CEST (Jul 21 2022 19:54:45 UTC)

// Verification Directory fv/mux 

module mux(idata_0, ivalid_0, ivch_0, idata_1, ivalid_1, ivch_1, sel,
     odata, ovalid, ovch);
  input [20:0] idata_0, idata_1;
  input ivalid_0, ivalid_1;
  input [1:0] ivch_0, ivch_1, sel;
  output [20:0] odata;
  output ovalid;
  output [1:0] ovch;
  wire [20:0] idata_0, idata_1;
  wire ivalid_0, ivalid_1;
  wire [1:0] ivch_0, ivch_1, sel;
  wire [20:0] odata;
  wire ovalid;
  wire [1:0] ovch;
  wire n_0, n_23, n_24;
  AO22D0BWP g604__2398(.A1 (n_24), .A2 (idata_1[14]), .B1
       (idata_0[14]), .B2 (n_23), .Z (odata[14]));
  AO22D0BWP g603__5107(.A1 (n_24), .A2 (idata_1[19]), .B1
       (idata_0[19]), .B2 (n_23), .Z (odata[19]));
  AO22D0BWP g615__6260(.A1 (n_24), .A2 (idata_1[18]), .B1
       (idata_0[18]), .B2 (n_23), .Z (odata[18]));
  AO22D0BWP g602__4319(.A1 (n_24), .A2 (idata_1[17]), .B1
       (idata_0[17]), .B2 (n_23), .Z (odata[17]));
  AO22D0BWP g616__8428(.A1 (n_24), .A2 (idata_1[16]), .B1
       (idata_0[16]), .B2 (n_23), .Z (odata[16]));
  AO22D0BWP g622__5526(.A1 (n_24), .A2 (idata_1[15]), .B1
       (idata_0[15]), .B2 (n_23), .Z (odata[15]));
  AO22D0BWP g608__6783(.A1 (n_24), .A2 (idata_1[20]), .B1
       (idata_0[20]), .B2 (n_23), .Z (odata[20]));
  AO22D0BWP g609__3680(.A1 (n_24), .A2 (idata_1[13]), .B1
       (idata_0[13]), .B2 (n_23), .Z (odata[13]));
  AO22D0BWP g612__1617(.A1 (n_24), .A2 (idata_1[12]), .B1
       (idata_0[12]), .B2 (n_23), .Z (odata[12]));
  AO22D0BWP g617__2802(.A1 (n_24), .A2 (idata_1[11]), .B1
       (idata_0[11]), .B2 (n_23), .Z (odata[11]));
  AO22D0BWP g619__1705(.A1 (n_24), .A2 (idata_1[10]), .B1
       (idata_0[10]), .B2 (n_23), .Z (odata[10]));
  AO22D0BWP g624__5122(.A1 (n_24), .A2 (idata_1[9]), .B1 (idata_0[9]),
       .B2 (n_23), .Z (odata[9]));
  AO22D0BWP g620__8246(.A1 (n_24), .A2 (idata_1[2]), .B1 (idata_0[2]),
       .B2 (n_23), .Z (odata[2]));
  AO22D0BWP g606__7098(.A1 (n_24), .A2 (idata_1[7]), .B1 (idata_0[7]),
       .B2 (n_23), .Z (odata[7]));
  AO22D0BWP g607__6131(.A1 (n_24), .A2 (idata_1[6]), .B1 (idata_0[6]),
       .B2 (n_23), .Z (odata[6]));
  AO22D0BWP g610__1881(.A1 (n_24), .A2 (idata_1[5]), .B1 (idata_0[5]),
       .B2 (n_23), .Z (odata[5]));
  AO22D0BWP g611__5115(.A1 (n_24), .A2 (idata_1[4]), .B1 (idata_0[4]),
       .B2 (n_23), .Z (odata[4]));
  AO22D0BWP g613__7482(.A1 (n_24), .A2 (idata_1[3]), .B1 (idata_0[3]),
       .B2 (n_23), .Z (odata[3]));
  AO22D0BWP g605__4733(.A1 (n_24), .A2 (idata_1[8]), .B1 (idata_0[8]),
       .B2 (n_23), .Z (odata[8]));
  AO22D0BWP g618__6161(.A1 (n_24), .A2 (idata_1[1]), .B1 (idata_0[1]),
       .B2 (n_23), .Z (odata[1]));
  AO22D0BWP g614__9315(.A1 (n_24), .A2 (idata_1[0]), .B1 (idata_0[0]),
       .B2 (n_23), .Z (odata[0]));
  AO22D0BWP g621__9945(.A1 (n_24), .A2 (ivalid_1), .B1 (ivalid_0), .B2
       (n_23), .Z (ovalid));
  AO22D0BWP g623__2883(.A1 (n_24), .A2 (ivch_1[1]), .B1 (ivch_0[1]),
       .B2 (n_23), .Z (ovch[1]));
  AO22D0BWP g625__2346(.A1 (n_24), .A2 (ivch_1[0]), .B1 (ivch_0[0]),
       .B2 (n_23), .Z (ovch[0]));
  CKAN2D1BWP g627__1666(.A1 (n_0), .A2 (sel[1]), .Z (n_24));
  INR2XD1BWP g626__7410(.A1 (sel[0]), .B1 (sel[1]), .ZN (n_23));
  CKND0BWP g628(.I (sel[0]), .ZN (n_0));
endmodule

