
// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Jul 20 2022 19:13:00 CEST (Jul 20 2022 17:13:00 UTC)

// Verification Directory fv/mux 

module mux(idata_0, ivalid_0, ivch_0, idata_1, ivalid_1, ivch_1,
     idata_2, ivalid_2, ivch_2, idata_3, ivalid_3, ivch_3, sel, odata,
     ovalid, ovch);
  input [64:0] idata_0, idata_1, idata_2, idata_3;
  input ivalid_0, ivalid_1, ivalid_2, ivalid_3;
  input [1:0] ivch_0, ivch_1, ivch_2, ivch_3;
  input [3:0] sel;
  output [64:0] odata;
  output ovalid;
  output [1:0] ovch;
  wire [64:0] idata_0, idata_1, idata_2, idata_3;
  wire ivalid_0, ivalid_1, ivalid_2, ivalid_3;
  wire [1:0] ivch_0, ivch_1, ivch_2, ivch_3;
  wire [3:0] sel;
  wire [64:0] odata;
  wire ovalid;
  wire [1:0] ovch;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_138, n_140, n_142;
  AO221D0BWP g3500__2398(.A1 (n_142), .A2 (idata_0[64]), .B1 (n_140),
       .B2 (idata_3[64]), .C (n_67), .Z (odata[64]));
  AO221D0BWP g3544__5107(.A1 (n_142), .A2 (idata_0[63]), .B1 (n_138),
       .B2 (idata_1[63]), .C (n_70), .Z (odata[63]));
  AO221D0BWP g3501__6260(.A1 (n_142), .A2 (idata_0[62]), .B1 (n_140),
       .B2 (idata_3[62]), .C (n_47), .Z (odata[62]));
  AO221D0BWP g3545__4319(.A1 (n_142), .A2 (idata_0[61]), .B1 (n_138),
       .B2 (idata_1[61]), .C (n_39), .Z (odata[61]));
  AO221D0BWP g3556__8428(.A1 (n_142), .A2 (idata_0[60]), .B1 (n_138),
       .B2 (idata_1[60]), .C (n_6), .Z (odata[60]));
  AO221D0BWP g3502__5526(.A1 (n_142), .A2 (idata_0[59]), .B1 (n_138),
       .B2 (idata_1[59]), .C (n_11), .Z (odata[59]));
  AO221D0BWP g3523__6783(.A1 (n_142), .A2 (idata_0[58]), .B1 (n_138),
       .B2 (idata_1[58]), .C (n_38), .Z (odata[58]));
  AO221D0BWP g3534__3680(.A1 (n_142), .A2 (idata_0[57]), .B1 (n_138),
       .B2 (idata_1[57]), .C (n_44), .Z (odata[57]));
  AO221D0BWP g3551__1617(.A1 (n_142), .A2 (idata_0[56]), .B1 (n_138),
       .B2 (idata_1[56]), .C (n_27), .Z (odata[56]));
  AO221D0BWP g3557__2802(.A1 (n_142), .A2 (idata_0[55]), .B1 (n_138),
       .B2 (idata_1[55]), .C (n_9), .Z (odata[55]));
  AO221D0BWP g3563__1705(.A1 (n_142), .A2 (idata_0[54]), .B1 (n_138),
       .B2 (idata_1[54]), .C (n_62), .Z (odata[54]));
  AO221D0BWP g3503__5122(.A1 (n_142), .A2 (idata_0[53]), .B1 (n_138),
       .B2 (idata_1[53]), .C (n_34), .Z (odata[53]));
  AO221D0BWP g3512__8246(.A1 (n_142), .A2 (idata_0[52]), .B1 (n_138),
       .B2 (idata_1[52]), .C (n_18), .Z (odata[52]));
  AO221D0BWP g3518__7098(.A1 (n_142), .A2 (idata_0[51]), .B1 (n_138),
       .B2 (idata_1[51]), .C (n_25), .Z (odata[51]));
  AO221D0BWP g3524__6131(.A1 (n_142), .A2 (idata_0[50]), .B1 (n_138),
       .B2 (idata_1[50]), .C (n_14), .Z (odata[50]));
  AO221D0BWP g3535__1881(.A1 (n_142), .A2 (idata_0[49]), .B1 (n_138),
       .B2 (idata_1[49]), .C (n_52), .Z (odata[49]));
  AO221D0BWP g3546__5115(.A1 (n_142), .A2 (idata_0[48]), .B1 (n_138),
       .B2 (idata_1[48]), .C (n_37), .Z (odata[48]));
  AO221D0BWP g3548__7482(.A1 (n_142), .A2 (idata_0[47]), .B1 (n_138),
       .B2 (idata_1[47]), .C (n_30), .Z (odata[47]));
  AO221D0BWP g3552__4733(.A1 (n_142), .A2 (idata_0[46]), .B1 (n_138),
       .B2 (idata_1[46]), .C (n_23), .Z (odata[46]));
  AO221D0BWP g3558__6161(.A1 (n_142), .A2 (idata_0[45]), .B1 (n_138),
       .B2 (idata_1[45]), .C (n_17), .Z (odata[45]));
  AO221D0BWP g3560__9315(.A1 (n_142), .A2 (idata_0[44]), .B1 (n_138),
       .B2 (idata_1[44]), .C (n_12), .Z (odata[44]));
  AO221D0BWP g3564__9945(.A1 (n_142), .A2 (idata_0[43]), .B1 (n_138),
       .B2 (idata_1[43]), .C (n_66), .Z (odata[43]));
  AO221D0BWP g3504__2883(.A1 (n_142), .A2 (idata_0[42]), .B1 (n_138),
       .B2 (idata_1[42]), .C (n_72), .Z (odata[42]));
  AO221D0BWP g3506__2346(.A1 (n_142), .A2 (idata_0[41]), .B1 (n_138),
       .B2 (idata_1[41]), .C (n_65), .Z (odata[41]));
  AO221D0BWP g3508__1666(.A1 (n_142), .A2 (idata_0[40]), .B1 (n_138),
       .B2 (idata_1[40]), .C (n_57), .Z (odata[40]));
  AO221D0BWP g3513__7410(.A1 (n_142), .A2 (idata_0[39]), .B1 (n_138),
       .B2 (idata_1[39]), .C (n_31), .Z (odata[39]));
  AO221D0BWP g3516__6417(.A1 (n_142), .A2 (idata_0[38]), .B1 (n_138),
       .B2 (idata_1[38]), .C (n_60), .Z (odata[38]));
  AO221D0BWP g3521__5477(.A1 (n_142), .A2 (idata_0[37]), .B1 (n_138),
       .B2 (idata_1[37]), .C (n_45), .Z (odata[37]));
  AO221D0BWP g3525__2398(.A1 (n_142), .A2 (idata_0[36]), .B1 (n_138),
       .B2 (idata_1[36]), .C (n_29), .Z (odata[36]));
  AO221D0BWP g3528__5107(.A1 (n_142), .A2 (idata_0[35]), .B1 (n_138),
       .B2 (idata_1[35]), .C (n_10), .Z (odata[35]));
  AO221D0BWP g3530__6260(.A1 (n_142), .A2 (idata_0[34]), .B1 (n_138),
       .B2 (idata_1[34]), .C (n_69), .Z (odata[34]));
  AO221D0BWP g3536__4319(.A1 (n_142), .A2 (idata_0[33]), .B1 (n_138),
       .B2 (idata_1[33]), .C (n_55), .Z (odata[33]));
  AO221D0BWP g3540__8428(.A1 (n_142), .A2 (idata_0[32]), .B1 (n_138),
       .B2 (idata_1[32]), .C (n_48), .Z (odata[32]));
  AO221D0BWP g3542__5526(.A1 (n_142), .A2 (idata_0[31]), .B1 (n_140),
       .B2 (idata_3[31]), .C (n_40), .Z (odata[31]));
  AO221D0BWP g3547__6783(.A1 (n_142), .A2 (idata_0[30]), .B1 (n_138),
       .B2 (idata_1[30]), .C (n_36), .Z (odata[30]));
  AO221D0BWP g3549__3680(.A1 (n_142), .A2 (idata_0[29]), .B1 (n_138),
       .B2 (idata_1[29]), .C (n_33), .Z (odata[29]));
  AO221D0BWP g3550__1617(.A1 (n_142), .A2 (idata_0[28]), .B1 (n_138),
       .B2 (idata_1[28]), .C (n_28), .Z (odata[28]));
  AO221D0BWP g3553__2802(.A1 (n_142), .A2 (idata_0[27]), .B1 (n_73),
       .B2 (idata_2[27]), .C (n_24), .Z (odata[27]));
  AO221D0BWP g3554__1705(.A1 (n_142), .A2 (idata_0[26]), .B1 (n_138),
       .B2 (idata_1[26]), .C (n_21), .Z (odata[26]));
  AO221D0BWP g3555__5122(.A1 (n_142), .A2 (idata_0[25]), .B1 (n_138),
       .B2 (idata_1[25]), .C (n_20), .Z (odata[25]));
  AO221D0BWP g3559__8246(.A1 (n_142), .A2 (idata_0[24]), .B1 (n_138),
       .B2 (idata_1[24]), .C (n_15), .Z (odata[24]));
  AO221D0BWP g3561__7098(.A1 (n_142), .A2 (idata_0[23]), .B1 (n_138),
       .B2 (idata_1[23]), .C (n_13), .Z (odata[23]));
  AO221D0BWP g3562__6131(.A1 (n_142), .A2 (idata_0[22]), .B1 (n_138),
       .B2 (idata_1[22]), .C (n_8), .Z (odata[22]));
  AO221D0BWP g3565__1881(.A1 (n_142), .A2 (idata_0[21]), .B1 (n_138),
       .B2 (idata_1[21]), .C (n_5), .Z (odata[21]));
  AO221D0BWP g3566__5115(.A1 (n_142), .A2 (idata_0[20]), .B1 (n_138),
       .B2 (idata_1[20]), .C (n_63), .Z (odata[20]));
  AO221D0BWP g3567__7482(.A1 (n_142), .A2 (idata_0[19]), .B1 (n_138),
       .B2 (idata_1[19]), .C (n_71), .Z (odata[19]));
  AO221D0BWP g3505__4733(.A1 (n_142), .A2 (idata_0[18]), .B1 (n_138),
       .B2 (idata_1[18]), .C (n_61), .Z (odata[18]));
  AO221D0BWP g3507__6161(.A1 (n_142), .A2 (idata_0[17]), .B1 (n_138),
       .B2 (idata_1[17]), .C (n_35), .Z (odata[17]));
  AO221D0BWP g3509__9315(.A1 (n_142), .A2 (idata_0[16]), .B1 (n_138),
       .B2 (idata_1[16]), .C (n_50), .Z (odata[16]));
  AO221D0BWP g3510__9945(.A1 (n_142), .A2 (idata_0[15]), .B1 (n_138),
       .B2 (idata_1[15]), .C (n_19), .Z (odata[15]));
  AO221D0BWP g3511__2883(.A1 (n_142), .A2 (idata_0[14]), .B1 (n_140),
       .B2 (idata_3[14]), .C (n_49), .Z (odata[14]));
  AO221D0BWP g3514__2346(.A1 (n_142), .A2 (idata_0[13]), .B1 (n_138),
       .B2 (idata_1[13]), .C (n_42), .Z (odata[13]));
  AO221D0BWP g3515__1666(.A1 (n_142), .A2 (idata_0[12]), .B1 (n_138),
       .B2 (idata_1[12]), .C (n_26), .Z (odata[12]));
  AO221D0BWP g3517__7410(.A1 (n_142), .A2 (idata_0[11]), .B1 (n_138),
       .B2 (idata_1[11]), .C (n_68), .Z (odata[11]));
  AO221D0BWP g3519__6417(.A1 (n_142), .A2 (idata_0[10]), .B1 (n_138),
       .B2 (idata_1[10]), .C (n_56), .Z (odata[10]));
  AO221D0BWP g3520__5477(.A1 (n_142), .A2 (idata_0[9]), .B1 (n_138),
       .B2 (idata_1[9]), .C (n_53), .Z (odata[9]));
  AO221D0BWP g3522__2398(.A1 (n_142), .A2 (idata_0[8]), .B1 (n_138),
       .B2 (idata_1[8]), .C (n_41), .Z (odata[8]));
  AO221D0BWP g3526__5107(.A1 (n_142), .A2 (idata_0[7]), .B1 (n_138),
       .B2 (idata_1[7]), .C (n_32), .Z (odata[7]));
  AO221D0BWP g3527__6260(.A1 (n_142), .A2 (idata_0[6]), .B1 (n_138),
       .B2 (idata_1[6]), .C (n_22), .Z (odata[6]));
  AO221D0BWP g3529__4319(.A1 (n_142), .A2 (idata_0[5]), .B1 (n_138),
       .B2 (idata_1[5]), .C (n_16), .Z (odata[5]));
  AO221D0BWP g3531__8428(.A1 (n_142), .A2 (idata_0[4]), .B1 (n_138),
       .B2 (idata_1[4]), .C (n_7), .Z (odata[4]));
  AO221D0BWP g3532__5526(.A1 (n_142), .A2 (idata_0[3]), .B1 (n_138),
       .B2 (idata_1[3]), .C (n_64), .Z (odata[3]));
  AO221D0BWP g3533__6783(.A1 (n_142), .A2 (idata_0[2]), .B1 (n_138),
       .B2 (idata_1[2]), .C (n_59), .Z (odata[2]));
  AO221D0BWP g3537__3680(.A1 (n_142), .A2 (idata_0[1]), .B1 (n_138),
       .B2 (idata_1[1]), .C (n_58), .Z (odata[1]));
  AO221D0BWP g3538__1617(.A1 (n_142), .A2 (idata_0[0]), .B1 (n_138),
       .B2 (idata_1[0]), .C (n_54), .Z (odata[0]));
  AO221D0BWP g3539__2802(.A1 (n_142), .A2 (ivalid_0), .B1 (n_140), .B2
       (ivalid_3), .C (n_51), .Z (ovalid));
  AO221D0BWP g3541__1705(.A1 (n_142), .A2 (ivch_0[1]), .B1 (n_140), .B2
       (ivch_3[1]), .C (n_46), .Z (ovch[1]));
  AO221D0BWP g3543__5122(.A1 (n_142), .A2 (ivch_0[0]), .B1 (n_73), .B2
       (ivch_2[0]), .C (n_43), .Z (ovch[0]));
  AO22D0BWP g3568__8246(.A1 (n_140), .A2 (idata_3[42]), .B1
       (idata_2[42]), .B2 (n_73), .Z (n_72));
  AO22D0BWP g3569__7098(.A1 (n_140), .A2 (idata_3[19]), .B1
       (idata_2[19]), .B2 (n_73), .Z (n_71));
  AO22D0BWP g3632__6131(.A1 (n_140), .A2 (idata_3[63]), .B1
       (idata_2[63]), .B2 (n_73), .Z (n_70));
  AO22D0BWP g3600__1881(.A1 (n_140), .A2 (idata_3[34]), .B1
       (idata_2[34]), .B2 (n_73), .Z (n_69));
  AO22D0BWP g3584__5115(.A1 (n_140), .A2 (idata_3[11]), .B1
       (idata_2[11]), .B2 (n_73), .Z (n_68));
  AO22D0BWP g3576__7482(.A1 (n_138), .A2 (idata_1[64]), .B1
       (idata_2[64]), .B2 (n_73), .Z (n_67));
  AO22D0BWP g3633__4733(.A1 (n_140), .A2 (idata_3[43]), .B1
       (idata_2[43]), .B2 (n_73), .Z (n_66));
  AO22D0BWP g3572__6161(.A1 (n_140), .A2 (idata_3[41]), .B1
       (idata_2[41]), .B2 (n_73), .Z (n_65));
  AO22D0BWP g3601__9315(.A1 (n_140), .A2 (idata_3[3]), .B1
       (idata_2[3]), .B2 (n_73), .Z (n_64));
  AO22D0BWP g3634__9945(.A1 (n_140), .A2 (idata_3[20]), .B1
       (idata_2[20]), .B2 (n_73), .Z (n_63));
  AO22D0BWP g3635__2883(.A1 (n_140), .A2 (idata_3[54]), .B1
       (idata_2[54]), .B2 (n_73), .Z (n_62));
  AO22D0BWP g3570__2346(.A1 (n_140), .A2 (idata_3[18]), .B1
       (idata_2[18]), .B2 (n_73), .Z (n_61));
  AO22D0BWP g3585__1666(.A1 (n_140), .A2 (idata_3[38]), .B1
       (idata_2[38]), .B2 (n_73), .Z (n_60));
  AO22D0BWP g3602__7410(.A1 (n_140), .A2 (idata_3[2]), .B1
       (idata_2[2]), .B2 (n_73), .Z (n_59));
  AO22D0BWP g3603__6417(.A1 (n_140), .A2 (idata_3[1]), .B1
       (idata_2[1]), .B2 (n_73), .Z (n_58));
  AO22D0BWP g3577__5477(.A1 (n_140), .A2 (idata_3[40]), .B1
       (idata_2[40]), .B2 (n_73), .Z (n_57));
  AO22D0BWP g3586__2398(.A1 (n_140), .A2 (idata_3[10]), .B1
       (idata_2[10]), .B2 (n_73), .Z (n_56));
  AO22D0BWP g3604__5107(.A1 (n_140), .A2 (idata_3[33]), .B1
       (idata_2[33]), .B2 (n_73), .Z (n_55));
  AO22D0BWP g3605__6260(.A1 (n_140), .A2 (idata_3[0]), .B1
       (idata_2[0]), .B2 (n_73), .Z (n_54));
  AO22D0BWP g3587__4319(.A1 (n_140), .A2 (idata_3[9]), .B1
       (idata_2[9]), .B2 (n_73), .Z (n_53));
  AO22D0BWP g3606__8428(.A1 (n_140), .A2 (idata_3[49]), .B1
       (idata_2[49]), .B2 (n_73), .Z (n_52));
  AO22D0BWP g3607__5526(.A1 (n_138), .A2 (ivalid_1), .B1 (ivalid_2),
       .B2 (n_73), .Z (n_51));
  AO22D0BWP g3573__6783(.A1 (n_140), .A2 (idata_3[16]), .B1
       (idata_2[16]), .B2 (n_73), .Z (n_50));
  AO22D0BWP g3578__3680(.A1 (n_138), .A2 (idata_1[14]), .B1
       (idata_2[14]), .B2 (n_73), .Z (n_49));
  AO22D0BWP g3608__1617(.A1 (n_140), .A2 (idata_3[32]), .B1
       (idata_2[32]), .B2 (n_73), .Z (n_48));
  AO22D0BWP g3588__2802(.A1 (n_138), .A2 (idata_1[62]), .B1
       (idata_2[62]), .B2 (n_73), .Z (n_47));
  AO22D0BWP g3609__1705(.A1 (n_138), .A2 (ivch_1[1]), .B1 (ivch_2[1]),
       .B2 (n_73), .Z (n_46));
  AO22D0BWP g3589__5122(.A1 (n_140), .A2 (idata_3[37]), .B1
       (idata_2[37]), .B2 (n_73), .Z (n_45));
  AO22D0BWP g3610__8246(.A1 (n_140), .A2 (idata_3[57]), .B1
       (idata_2[57]), .B2 (n_73), .Z (n_44));
  AO22D0BWP g3611__7098(.A1 (n_138), .A2 (ivch_1[0]), .B1 (ivch_3[0]),
       .B2 (n_140), .Z (n_43));
  AO22D0BWP g3579__6131(.A1 (n_140), .A2 (idata_3[13]), .B1
       (idata_2[13]), .B2 (n_73), .Z (n_42));
  AO22D0BWP g3590__1881(.A1 (n_140), .A2 (idata_3[8]), .B1
       (idata_2[8]), .B2 (n_73), .Z (n_41));
  AO22D0BWP g3612__5115(.A1 (n_138), .A2 (idata_1[31]), .B1
       (idata_2[31]), .B2 (n_73), .Z (n_40));
  AO22D0BWP g3613__7482(.A1 (n_140), .A2 (idata_3[61]), .B1
       (idata_2[61]), .B2 (n_73), .Z (n_39));
  AO22D0BWP g3591__4733(.A1 (n_140), .A2 (idata_3[58]), .B1
       (idata_2[58]), .B2 (n_73), .Z (n_38));
  AO22D0BWP g3614__6161(.A1 (n_140), .A2 (idata_3[48]), .B1
       (idata_2[48]), .B2 (n_73), .Z (n_37));
  AO22D0BWP g3615__9315(.A1 (n_140), .A2 (idata_3[30]), .B1
       (idata_2[30]), .B2 (n_73), .Z (n_36));
  AO22D0BWP g3571__9945(.A1 (n_140), .A2 (idata_3[17]), .B1
       (idata_2[17]), .B2 (n_73), .Z (n_35));
  AO22D0BWP g3574__2883(.A1 (n_140), .A2 (idata_3[53]), .B1
       (idata_2[53]), .B2 (n_73), .Z (n_34));
  AO22D0BWP g3616__2346(.A1 (n_140), .A2 (idata_3[29]), .B1
       (idata_2[29]), .B2 (n_73), .Z (n_33));
  AO22D0BWP g3592__1666(.A1 (n_140), .A2 (idata_3[7]), .B1
       (idata_2[7]), .B2 (n_73), .Z (n_32));
  AO22D0BWP g3580__7410(.A1 (n_140), .A2 (idata_3[39]), .B1
       (idata_2[39]), .B2 (n_73), .Z (n_31));
  AO22D0BWP g3617__6417(.A1 (n_140), .A2 (idata_3[47]), .B1
       (idata_2[47]), .B2 (n_73), .Z (n_30));
  AO22D0BWP g3593__5477(.A1 (n_140), .A2 (idata_3[36]), .B1
       (idata_2[36]), .B2 (n_73), .Z (n_29));
  AO22D0BWP g3618__2398(.A1 (n_140), .A2 (idata_3[28]), .B1
       (idata_2[28]), .B2 (n_73), .Z (n_28));
  AO22D0BWP g3619__5107(.A1 (n_140), .A2 (idata_3[56]), .B1
       (idata_2[56]), .B2 (n_73), .Z (n_27));
  AO22D0BWP g3581__6260(.A1 (n_140), .A2 (idata_3[12]), .B1
       (idata_2[12]), .B2 (n_73), .Z (n_26));
  AO22D0BWP g3594__4319(.A1 (n_140), .A2 (idata_3[51]), .B1
       (idata_2[51]), .B2 (n_73), .Z (n_25));
  AO22D0BWP g3620__8428(.A1 (n_138), .A2 (idata_1[27]), .B1
       (idata_3[27]), .B2 (n_140), .Z (n_24));
  AO22D0BWP g3621__5526(.A1 (n_140), .A2 (idata_3[46]), .B1
       (idata_2[46]), .B2 (n_73), .Z (n_23));
  AO22D0BWP g3595__6783(.A1 (n_140), .A2 (idata_3[6]), .B1
       (idata_2[6]), .B2 (n_73), .Z (n_22));
  AO22D0BWP g3622__3680(.A1 (n_140), .A2 (idata_3[26]), .B1
       (idata_2[26]), .B2 (n_73), .Z (n_21));
  AO22D0BWP g3623__1617(.A1 (n_140), .A2 (idata_3[25]), .B1
       (idata_2[25]), .B2 (n_73), .Z (n_20));
  AO22D0BWP g3575__2802(.A1 (n_140), .A2 (idata_3[15]), .B1
       (idata_2[15]), .B2 (n_73), .Z (n_19));
  AO22D0BWP g3582__1705(.A1 (n_140), .A2 (idata_3[52]), .B1
       (idata_2[52]), .B2 (n_73), .Z (n_18));
  AO22D0BWP g3624__5122(.A1 (n_140), .A2 (idata_3[45]), .B1
       (idata_2[45]), .B2 (n_73), .Z (n_17));
  AO22D0BWP g3596__8246(.A1 (n_140), .A2 (idata_3[5]), .B1
       (idata_2[5]), .B2 (n_73), .Z (n_16));
  AO22D0BWP g3625__7098(.A1 (n_140), .A2 (idata_3[24]), .B1
       (idata_2[24]), .B2 (n_73), .Z (n_15));
  AO22D0BWP g3597__6131(.A1 (n_140), .A2 (idata_3[50]), .B1
       (idata_2[50]), .B2 (n_73), .Z (n_14));
  AO22D0BWP g3626__1881(.A1 (n_140), .A2 (idata_3[23]), .B1
       (idata_2[23]), .B2 (n_73), .Z (n_13));
  AO22D0BWP g3627__5115(.A1 (n_140), .A2 (idata_3[44]), .B1
       (idata_2[44]), .B2 (n_73), .Z (n_12));
  AO22D0BWP g3583__7482(.A1 (n_140), .A2 (idata_3[59]), .B1
       (idata_2[59]), .B2 (n_73), .Z (n_11));
  AO22D0BWP g3598__4733(.A1 (n_140), .A2 (idata_3[35]), .B1
       (idata_2[35]), .B2 (n_73), .Z (n_10));
  AO22D0BWP g3628__6161(.A1 (n_140), .A2 (idata_3[55]), .B1
       (idata_2[55]), .B2 (n_73), .Z (n_9));
  AO22D0BWP g3629__9315(.A1 (n_140), .A2 (idata_3[22]), .B1
       (idata_2[22]), .B2 (n_73), .Z (n_8));
  AO22D0BWP g3599__9945(.A1 (n_140), .A2 (idata_3[4]), .B1
       (idata_2[4]), .B2 (n_73), .Z (n_7));
  AO22D0BWP g3630__2883(.A1 (n_140), .A2 (idata_3[60]), .B1
       (idata_2[60]), .B2 (n_73), .Z (n_6));
  AO22D0BWP g3631__2346(.A1 (n_140), .A2 (idata_3[21]), .B1
       (idata_2[21]), .B2 (n_73), .Z (n_5));
  CKAN2D4BWP g3639__1666(.A1 (n_3), .A2 (sel[0]), .Z (n_142));
  CKAN2D4BWP g3636__7410(.A1 (n_1), .A2 (n_4), .Z (n_140));
  CKAN2D4BWP g3637__6417(.A1 (n_0), .A2 (n_4), .Z (n_73));
  AN3D4BWP g3638__5477(.A1 (n_2), .A2 (n_4), .A3 (sel[1]), .Z (n_138));
  INR2XD0BWP g3640__2398(.A1 (n_2), .B1 (sel[1]), .ZN (n_3));
  INR3D0BWP g3641__5107(.A1 (sel[3]), .B1 (sel[2]), .B2 (sel[1]), .ZN
       (n_1));
  INR3D0BWP g3642__6260(.A1 (sel[2]), .B1 (sel[3]), .B2 (sel[1]), .ZN
       (n_0));
  NR2D0BWP g3643__4319(.A1 (sel[3]), .A2 (sel[2]), .ZN (n_2));
  CKND0BWP g3644(.I (sel[0]), .ZN (n_4));
endmodule

