
// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Jul  7 2022 13:49:12 CEST (Jul  7 2022 11:49:12 UTC)

// Verification Directory fv/mux 

module mux(idata_0, ivalid_0, ivch_0, idata_1, ivalid_1, ivch_1,
     idata_2, ivalid_2, ivch_2, idata_3, ivalid_3, ivch_3, idata_4,
     ivalid_4, ivch_4, sel, odata, ovalid, ovch);
  input [34:0] idata_0, idata_1, idata_2, idata_3, idata_4;
  input ivalid_0, ivalid_1, ivalid_2, ivalid_3, ivalid_4;
  input [1:0] ivch_0, ivch_1, ivch_2, ivch_3, ivch_4;
  input [4:0] sel;
  output [34:0] odata;
  output ovalid;
  output [1:0] ovch;
  wire [34:0] idata_0, idata_1, idata_2, idata_3, idata_4;
  wire ivalid_0, ivalid_1, ivalid_2, ivalid_3, ivalid_4;
  wire [1:0] ivch_0, ivch_1, ivch_2, ivch_3, ivch_4;
  wire [4:0] sel;
  wire [34:0] odata;
  wire ovalid;
  wire [1:0] ovch;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_74, n_78, n_80;
  wire n_83, n_85;
  AO221D0BWP g2592__2398(.A1 (n_85), .A2 (idata_4[25]), .B1 (n_83), .B2
       (idata_2[25]), .C (n_10), .Z (odata[25]));
  AO221D0BWP g2583__5107(.A1 (n_85), .A2 (idata_4[33]), .B1 (n_80), .B2
       (idata_0[33]), .C (n_23), .Z (odata[33]));
  AO221D0BWP g2604__6260(.A1 (n_83), .A2 (idata_2[32]), .B1 (n_78), .B2
       (idata_1[32]), .C (n_20), .Z (odata[32]));
  AO221D0BWP g2584__4319(.A1 (n_85), .A2 (idata_4[31]), .B1 (n_83), .B2
       (idata_2[31]), .C (n_21), .Z (odata[31]));
  AO221D0BWP g2582__8428(.A1 (n_83), .A2 (idata_2[30]), .B1 (n_80), .B2
       (idata_0[30]), .C (n_39), .Z (odata[30]));
  AO221D0BWP g2596__5526(.A1 (n_85), .A2 (idata_4[29]), .B1 (n_78), .B2
       (idata_1[29]), .C (n_44), .Z (odata[29]));
  AO221D0BWP g2605__6783(.A1 (n_80), .A2 (idata_0[28]), .B1 (n_78), .B2
       (idata_1[28]), .C (n_28), .Z (odata[28]));
  AO221D0BWP g2613__3680(.A1 (n_80), .A2 (idata_0[27]), .B1 (n_74), .B2
       (idata_3[27]), .C (n_25), .Z (odata[27]));
  AO221D0BWP g2585__1617(.A1 (n_74), .A2 (idata_3[26]), .B1 (n_78), .B2
       (idata_1[26]), .C (n_40), .Z (odata[26]));
  AO221D0BWP g2591__2802(.A1 (n_85), .A2 (idata_4[34]), .B1 (n_83), .B2
       (idata_2[34]), .C (n_15), .Z (odata[34]));
  AO221D0BWP g2597__1705(.A1 (n_85), .A2 (idata_4[24]), .B1 (n_78), .B2
       (idata_1[24]), .C (n_32), .Z (odata[24]));
  AO221D0BWP g2600__5122(.A1 (n_83), .A2 (idata_2[23]), .B1 (n_74), .B2
       (idata_3[23]), .C (n_18), .Z (odata[23]));
  AO221D0BWP g2602__8246(.A1 (n_83), .A2 (idata_2[22]), .B1 (n_74), .B2
       (idata_3[22]), .C (n_7), .Z (odata[22]));
  AO221D0BWP g2606__7098(.A1 (n_80), .A2 (idata_0[21]), .B1 (n_74), .B2
       (idata_3[21]), .C (n_38), .Z (odata[21]));
  AO221D0BWP g2601__6131(.A1 (n_85), .A2 (idata_4[20]), .B1 (n_78), .B2
       (idata_1[20]), .C (n_11), .Z (odata[20]));
  AO221D0BWP g2614__1881(.A1 (n_74), .A2 (idata_3[19]), .B1 (n_78), .B2
       (idata_1[19]), .C (n_27), .Z (odata[19]));
  AO221D0BWP g2617__5115(.A1 (n_85), .A2 (idata_4[18]), .B1 (n_80), .B2
       (idata_0[18]), .C (n_13), .Z (odata[18]));
  AO221D0BWP g2586__7482(.A1 (n_85), .A2 (idata_4[17]), .B1 (n_80), .B2
       (idata_0[17]), .C (n_41), .Z (odata[17]));
  AO221D0BWP g2590__4733(.A1 (n_85), .A2 (idata_4[16]), .B1 (n_80), .B2
       (idata_0[16]), .C (n_33), .Z (odata[16]));
  AO221D0BWP g2609__6161(.A1 (n_83), .A2 (idata_2[6]), .B1 (n_78), .B2
       (idata_1[6]), .C (n_42), .Z (odata[6]));
  AO221D0BWP g2594__9315(.A1 (n_83), .A2 (idata_2[14]), .B1 (n_74), .B2
       (idata_3[14]), .C (n_26), .Z (odata[14]));
  AO221D0BWP g2595__9945(.A1 (n_85), .A2 (idata_4[13]), .B1 (n_78), .B2
       (idata_1[13]), .C (n_35), .Z (odata[13]));
  AO221D0BWP g2598__2883(.A1 (n_80), .A2 (idata_0[12]), .B1 (n_74), .B2
       (idata_3[12]), .C (n_36), .Z (odata[12]));
  AO221D0BWP g2599__2346(.A1 (n_80), .A2 (idata_0[11]), .B1 (n_74), .B2
       (idata_3[11]), .C (n_29), .Z (odata[11]));
  AO221D0BWP g2610__1666(.A1 (n_83), .A2 (idata_2[10]), .B1 (n_80), .B2
       (idata_0[10]), .C (n_14), .Z (odata[10]));
  AO221D0BWP g2603__7410(.A1 (n_74), .A2 (idata_3[9]), .B1 (n_78), .B2
       (idata_1[9]), .C (n_31), .Z (odata[9]));
  AO221D0BWP g2607__6417(.A1 (n_83), .A2 (idata_2[8]), .B1 (n_78), .B2
       (idata_1[8]), .C (n_8), .Z (odata[8]));
  AO221D0BWP g2608__5477(.A1 (n_80), .A2 (idata_0[7]), .B1 (n_74), .B2
       (idata_3[7]), .C (n_43), .Z (odata[7]));
  AO221D0BWP g2593__2398(.A1 (n_83), .A2 (idata_2[15]), .B1 (n_78), .B2
       (idata_1[15]), .C (n_22), .Z (odata[15]));
  AO221D0BWP g2611__5107(.A1 (n_83), .A2 (idata_2[5]), .B1 (n_80), .B2
       (idata_0[5]), .C (n_37), .Z (odata[5]));
  AO221D0BWP g2612__6260(.A1 (n_83), .A2 (idata_2[4]), .B1 (n_78), .B2
       (idata_1[4]), .C (n_34), .Z (odata[4]));
  AO221D0BWP g2615__4319(.A1 (n_85), .A2 (idata_4[3]), .B1 (n_78), .B2
       (idata_1[3]), .C (n_30), .Z (odata[3]));
  AO221D0BWP g2616__8428(.A1 (n_85), .A2 (idata_4[2]), .B1 (n_78), .B2
       (idata_1[2]), .C (n_24), .Z (odata[2]));
  AO221D0BWP g2618__5526(.A1 (n_74), .A2 (idata_3[1]), .B1 (n_78), .B2
       (idata_1[1]), .C (n_17), .Z (odata[1]));
  AO221D0BWP g2619__6783(.A1 (n_80), .A2 (idata_0[0]), .B1 (n_74), .B2
       (idata_3[0]), .C (n_12), .Z (odata[0]));
  AO221D0BWP g2587__3680(.A1 (n_80), .A2 (ivalid_0), .B1 (n_74), .B2
       (ivalid_3), .C (n_16), .Z (ovalid));
  AO221D0BWP g2588__1617(.A1 (n_85), .A2 (ivch_4[1]), .B1 (n_78), .B2
       (ivch_1[1]), .C (n_19), .Z (ovch[1]));
  AO221D0BWP g2589__2802(.A1 (n_85), .A2 (ivch_4[0]), .B1 (n_83), .B2
       (ivch_2[0]), .C (n_9), .Z (ovch[0]));
  AO222D0BWP g2646__1705(.A1 (n_83), .A2 (idata_2[29]), .B1 (n_80), .B2
       (idata_0[29]), .C1 (n_74), .C2 (idata_3[29]), .Z (n_44));
  AO222D0BWP g2642__5122(.A1 (n_85), .A2 (idata_4[7]), .B1 (n_83), .B2
       (idata_2[7]), .C1 (n_78), .C2 (idata_1[7]), .Z (n_43));
  AO222D0BWP g2643__8246(.A1 (n_85), .A2 (idata_4[6]), .B1 (n_74), .B2
       (idata_3[6]), .C1 (n_80), .C2 (idata_0[6]), .Z (n_42));
  AO222D0BWP g2623__7098(.A1 (n_83), .A2 (idata_2[17]), .B1 (n_74), .B2
       (idata_3[17]), .C1 (n_78), .C2 (idata_1[17]), .Z (n_41));
  AO222D0BWP g2626__6131(.A1 (n_85), .A2 (idata_4[26]), .B1 (n_80), .B2
       (idata_0[26]), .C1 (n_83), .C2 (idata_2[26]), .Z (n_40));
  AO222D0BWP g2632__1881(.A1 (n_85), .A2 (idata_4[30]), .B1 (n_78), .B2
       (idata_1[30]), .C1 (n_74), .C2 (idata_3[30]), .Z (n_39));
  AO222D0BWP g2644__5115(.A1 (n_85), .A2 (idata_4[21]), .B1 (n_78), .B2
       (idata_1[21]), .C1 (n_83), .C2 (idata_2[21]), .Z (n_38));
  AO222D0BWP g2645__7482(.A1 (n_85), .A2 (idata_4[5]), .B1 (n_78), .B2
       (idata_1[5]), .C1 (n_74), .C2 (idata_3[5]), .Z (n_37));
  AO222D0BWP g2633__4733(.A1 (n_85), .A2 (idata_4[12]), .B1 (n_83), .B2
       (idata_2[12]), .C1 (n_78), .C2 (idata_1[12]), .Z (n_36));
  AO222D0BWP g2631__6161(.A1 (n_83), .A2 (idata_2[13]), .B1 (n_74), .B2
       (idata_3[13]), .C1 (n_80), .C2 (idata_0[13]), .Z (n_35));
  AO222D0BWP g2647__9315(.A1 (n_85), .A2 (idata_4[4]), .B1 (n_80), .B2
       (idata_0[4]), .C1 (n_74), .C2 (idata_3[4]), .Z (n_34));
  AO222D0BWP g2627__9945(.A1 (n_83), .A2 (idata_2[16]), .B1 (n_74), .B2
       (idata_3[16]), .C1 (n_78), .C2 (idata_1[16]), .Z (n_33));
  AO222D0BWP g2634__2883(.A1 (n_83), .A2 (idata_2[24]), .B1 (n_80), .B2
       (idata_0[24]), .C1 (n_74), .C2 (idata_3[24]), .Z (n_32));
  AO222D0BWP g2648__2346(.A1 (n_85), .A2 (idata_4[9]), .B1 (n_80), .B2
       (idata_0[9]), .C1 (n_83), .C2 (idata_2[9]), .Z (n_31));
  AO222D0BWP g2649__1666(.A1 (n_80), .A2 (idata_0[3]), .B1 (n_83), .B2
       (idata_2[3]), .C1 (n_74), .C2 (idata_3[3]), .Z (n_30));
  AO222D0BWP g2635__7410(.A1 (n_85), .A2 (idata_4[11]), .B1 (n_78), .B2
       (idata_1[11]), .C1 (n_83), .C2 (idata_2[11]), .Z (n_29));
  AO222D0BWP g2650__6417(.A1 (n_85), .A2 (idata_4[28]), .B1 (n_83), .B2
       (idata_2[28]), .C1 (n_74), .C2 (idata_3[28]), .Z (n_28));
  AO222D0BWP g2651__5477(.A1 (n_85), .A2 (idata_4[19]), .B1 (n_80), .B2
       (idata_0[19]), .C1 (n_83), .C2 (idata_2[19]), .Z (n_27));
  AO222D0BWP g2620__2398(.A1 (n_85), .A2 (idata_4[14]), .B1 (n_78), .B2
       (idata_1[14]), .C1 (n_80), .C2 (idata_0[14]), .Z (n_26));
  AO222D0BWP g2655__5107(.A1 (n_85), .A2 (idata_4[27]), .B1 (n_78), .B2
       (idata_1[27]), .C1 (n_83), .C2 (idata_2[27]), .Z (n_25));
  AO222D0BWP g2652__6260(.A1 (n_83), .A2 (idata_2[2]), .B1 (n_80), .B2
       (idata_0[2]), .C1 (n_74), .C2 (idata_3[2]), .Z (n_24));
  AO222D0BWP g2636__4319(.A1 (n_83), .A2 (idata_2[33]), .B1 (n_78), .B2
       (idata_1[33]), .C1 (n_74), .C2 (idata_3[33]), .Z (n_23));
  AO222D0BWP g2628__8428(.A1 (n_85), .A2 (idata_4[15]), .B1 (n_74), .B2
       (idata_3[15]), .C1 (n_80), .C2 (idata_0[15]), .Z (n_22));
  AO222D0BWP g2624__5526(.A1 (n_74), .A2 (idata_3[31]), .B1 (n_80), .B2
       (idata_0[31]), .C1 (n_78), .C2 (idata_1[31]), .Z (n_21));
  AO222D0BWP g2653__6783(.A1 (n_85), .A2 (idata_4[32]), .B1 (n_74), .B2
       (idata_3[32]), .C1 (n_80), .C2 (idata_0[32]), .Z (n_20));
  AO222D0BWP g2622__3680(.A1 (n_83), .A2 (ivch_2[1]), .B1 (n_74), .B2
       (ivch_3[1]), .C1 (n_80), .C2 (ivch_0[1]), .Z (n_19));
  AO222D0BWP g2637__1617(.A1 (n_85), .A2 (idata_4[23]), .B1 (n_78), .B2
       (idata_1[23]), .C1 (n_80), .C2 (idata_0[23]), .Z (n_18));
  AO222D0BWP g2654__2802(.A1 (n_85), .A2 (idata_4[1]), .B1 (n_80), .B2
       (idata_0[1]), .C1 (n_83), .C2 (idata_2[1]), .Z (n_17));
  AO222D0BWP g2621__1705(.A1 (n_85), .A2 (ivalid_4), .B1 (n_83), .B2
       (ivalid_2), .C1 (n_78), .C2 (ivalid_1), .Z (n_16));
  AO222D0BWP g2629__5122(.A1 (n_74), .A2 (idata_3[34]), .B1 (n_80), .B2
       (idata_0[34]), .C1 (n_78), .C2 (idata_1[34]), .Z (n_15));
  AO222D0BWP g2638__8246(.A1 (n_85), .A2 (idata_4[10]), .B1 (n_74), .B2
       (idata_3[10]), .C1 (n_78), .C2 (idata_1[10]), .Z (n_14));
  AO222D0BWP g2656__7098(.A1 (n_83), .A2 (idata_2[18]), .B1 (n_74), .B2
       (idata_3[18]), .C1 (n_78), .C2 (idata_1[18]), .Z (n_13));
  AO222D0BWP g2657__6131(.A1 (n_85), .A2 (idata_4[0]), .B1 (n_83), .B2
       (idata_2[0]), .C1 (n_78), .C2 (idata_1[0]), .Z (n_12));
  AO222D0BWP g2639__1881(.A1 (n_80), .A2 (idata_0[20]), .B1 (n_83), .B2
       (idata_2[20]), .C1 (n_74), .C2 (idata_3[20]), .Z (n_11));
  AO222D0BWP g2630__5115(.A1 (n_80), .A2 (idata_0[25]), .B1 (n_78), .B2
       (idata_1[25]), .C1 (n_74), .C2 (idata_3[25]), .Z (n_10));
  AO222D0BWP g2625__7482(.A1 (n_80), .A2 (ivch_0[0]), .B1 (n_74), .B2
       (ivch_3[0]), .C1 (n_78), .C2 (ivch_1[0]), .Z (n_9));
  AO222D0BWP g2640__4733(.A1 (n_85), .A2 (idata_4[8]), .B1 (n_74), .B2
       (idata_3[8]), .C1 (n_80), .C2 (idata_0[8]), .Z (n_8));
  AO222D0BWP g2641__6161(.A1 (n_85), .A2 (idata_4[22]), .B1 (n_78), .B2
       (idata_1[22]), .C1 (n_80), .C2 (idata_0[22]), .Z (n_7));
  AN4D2BWP g2661__9315(.A1 (n_6), .A2 (n_5), .A3 (n_3), .A4 (sel[0]),
       .Z (n_80));
  AN3D2BWP g2662__9945(.A1 (n_6), .A2 (n_4), .A3 (sel[4]), .Z (n_85));
  AN4D2BWP g2659__2883(.A1 (n_6), .A2 (n_5), .A3 (n_2), .A4 (sel[1]),
       .Z (n_78));
  AN4D2BWP g2658__2346(.A1 (n_4), .A2 (n_5), .A3 (n_1), .A4 (sel[3]),
       .Z (n_74));
  AN4D2BWP g2660__1666(.A1 (n_4), .A2 (n_5), .A3 (n_0), .A4 (sel[2]),
       .Z (n_83));
  NR2D0BWP g2663__7410(.A1 (sel[3]), .A2 (sel[2]), .ZN (n_6));
  NR2D0BWP g2664__6417(.A1 (sel[1]), .A2 (sel[0]), .ZN (n_4));
  CKND0BWP g2666(.I (sel[1]), .ZN (n_3));
  CKND0BWP g2667(.I (sel[0]), .ZN (n_2));
  CKND0BWP g2668(.I (sel[2]), .ZN (n_1));
  CKND0BWP g2669(.I (sel[3]), .ZN (n_0));
  CKND0BWP g2665(.I (sel[4]), .ZN (n_5));
endmodule

