
// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Jul 21 2022 21:47:49 CEST (Jul 21 2022 19:47:49 UTC)

// Verification Directory fv/mux 

module mux(idata_0, ivalid_0, ivch_0, idata_1, ivalid_1, ivch_1, sel,
     odata, ovalid, ovch);
  input [16:0] idata_0, idata_1;
  input ivalid_0, ivalid_1;
  input [1:0] ivch_0, ivch_1, sel;
  output [16:0] odata;
  output ovalid;
  output [1:0] ovch;
  wire [16:0] idata_0, idata_1;
  wire ivalid_0, ivalid_1;
  wire [1:0] ivch_0, ivch_1, sel;
  wire [16:0] odata;
  wire ovalid;
  wire [1:0] ovch;
  wire n_18, n_19;
  AO22D0BWP g510__2398(.A1 (n_19), .A2 (idata_1[16]), .B1
       (idata_0[16]), .B2 (n_18), .Z (odata[16]));
  AO22D0BWP g511__5107(.A1 (n_19), .A2 (idata_1[15]), .B1
       (idata_0[15]), .B2 (n_18), .Z (odata[15]));
  AO22D0BWP g523__6260(.A1 (n_19), .A2 (idata_1[14]), .B1
       (idata_0[14]), .B2 (n_18), .Z (odata[14]));
  AO22D0BWP g516__4319(.A1 (n_19), .A2 (idata_1[13]), .B1
       (idata_0[13]), .B2 (n_18), .Z (odata[13]));
  AO22D0BWP g524__8428(.A1 (n_19), .A2 (idata_1[12]), .B1
       (idata_0[12]), .B2 (n_18), .Z (odata[12]));
  AO22D0BWP g528__5526(.A1 (n_19), .A2 (idata_1[11]), .B1
       (idata_0[11]), .B2 (n_18), .Z (odata[11]));
  AO22D0BWP g512__6783(.A1 (n_19), .A2 (idata_1[10]), .B1
       (idata_0[10]), .B2 (n_18), .Z (odata[10]));
  AO22D0BWP g517__3680(.A1 (n_19), .A2 (idata_1[9]), .B1 (idata_0[9]),
       .B2 (n_18), .Z (odata[9]));
  AO22D0BWP g520__1617(.A1 (n_19), .A2 (idata_1[8]), .B1 (idata_0[8]),
       .B2 (n_18), .Z (odata[8]));
  AO22D0BWP g525__2802(.A1 (n_19), .A2 (idata_1[7]), .B1 (idata_0[7]),
       .B2 (n_18), .Z (odata[7]));
  AO22D0BWP g527__1705(.A1 (n_19), .A2 (idata_1[6]), .B1 (idata_0[6]),
       .B2 (n_18), .Z (odata[6]));
  AO22D0BWP g529__5122(.A1 (n_19), .A2 (idata_1[5]), .B1 (idata_0[5]),
       .B2 (n_18), .Z (odata[5]));
  AO22D0BWP g513__8246(.A1 (n_19), .A2 (idata_1[4]), .B1 (idata_0[4]),
       .B2 (n_18), .Z (odata[4]));
  AO22D0BWP g514__7098(.A1 (n_19), .A2 (idata_1[3]), .B1 (idata_0[3]),
       .B2 (n_18), .Z (odata[3]));
  AO22D0BWP g515__6131(.A1 (n_19), .A2 (idata_1[2]), .B1 (idata_0[2]),
       .B2 (n_18), .Z (odata[2]));
  AO22D0BWP g518__1881(.A1 (n_19), .A2 (idata_1[1]), .B1 (idata_0[1]),
       .B2 (n_18), .Z (odata[1]));
  AO22D0BWP g519__5115(.A1 (n_19), .A2 (idata_1[0]), .B1 (idata_0[0]),
       .B2 (n_18), .Z (odata[0]));
  AO22D0BWP g521__7482(.A1 (n_19), .A2 (ivalid_1), .B1 (ivalid_0), .B2
       (n_18), .Z (ovalid));
  AO22D0BWP g522__4733(.A1 (n_19), .A2 (ivch_1[1]), .B1 (ivch_0[1]),
       .B2 (n_18), .Z (ovch[1]));
  AO22D0BWP g526__6161(.A1 (n_19), .A2 (ivch_1[0]), .B1 (ivch_0[0]),
       .B2 (n_18), .Z (ovch[0]));
  INR2XD1BWP g530__9315(.A1 (sel[0]), .B1 (sel[1]), .ZN (n_18));
  INR2XD1BWP g531__9945(.A1 (sel[1]), .B1 (sel[0]), .ZN (n_19));
endmodule

