
// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Jul 20 2022 12:39:07 CEST (Jul 20 2022 10:39:07 UTC)

// Verification Directory fv/mux 

module mux(idata_0, ivalid_0, ivch_0, idata_1, ivalid_1, ivch_1,
     idata_2, ivalid_2, ivch_2, sel, odata, ovalid, ovch);
  input [31:0] idata_0, idata_1, idata_2;
  input ivalid_0, ivalid_1, ivalid_2;
  input [1:0] ivch_0, ivch_1, ivch_2;
  input [2:0] sel;
  output [31:0] odata;
  output ovalid;
  output [1:0] ovch;
  wire [31:0] idata_0, idata_1, idata_2;
  wire ivalid_0, ivalid_1, ivalid_2;
  wire [1:0] ivch_0, ivch_1, ivch_2;
  wire [2:0] sel;
  wire [31:0] odata;
  wire ovalid;
  wire [1:0] ovch;
  wire n_0, n_1, n_2, n_3, n_37, n_38, n_39;
  AO222D0BWP g1436__2398(.A1 (n_37), .A2 (idata_2[31]), .B1 (n_38), .B2
       (idata_0[31]), .C1 (n_39), .C2 (idata_1[31]), .Z (odata[31]));
  AO222D0BWP g1437__5107(.A1 (n_39), .A2 (idata_1[30]), .B1 (n_38), .B2
       (idata_0[30]), .C1 (n_37), .C2 (idata_2[30]), .Z (odata[30]));
  AO222D0BWP g1456__6260(.A1 (n_37), .A2 (idata_2[29]), .B1 (n_38), .B2
       (idata_0[29]), .C1 (n_39), .C2 (idata_1[29]), .Z (odata[29]));
  AO222D0BWP g1438__4319(.A1 (n_39), .A2 (idata_1[28]), .B1 (n_38), .B2
       (idata_0[28]), .C1 (n_37), .C2 (idata_2[28]), .Z (odata[28]));
  AO222D0BWP g1449__8428(.A1 (n_39), .A2 (idata_1[27]), .B1 (n_38), .B2
       (idata_0[27]), .C1 (n_37), .C2 (idata_2[27]), .Z (odata[27]));
  AO222D0BWP g1457__5526(.A1 (n_37), .A2 (idata_2[26]), .B1 (n_38), .B2
       (idata_0[26]), .C1 (n_39), .C2 (idata_1[26]), .Z (odata[26]));
  AO222D0BWP g1464__6783(.A1 (n_37), .A2 (idata_2[25]), .B1 (n_38), .B2
       (idata_0[25]), .C1 (n_39), .C2 (idata_1[25]), .Z (odata[25]));
  AO222D0BWP g1439__3680(.A1 (n_39), .A2 (idata_1[24]), .B1 (n_38), .B2
       (idata_0[24]), .C1 (n_37), .C2 (idata_2[24]), .Z (odata[24]));
  AO222D0BWP g1446__1617(.A1 (n_37), .A2 (idata_2[23]), .B1 (n_38), .B2
       (idata_0[23]), .C1 (n_39), .C2 (idata_1[23]), .Z (odata[23]));
  AO222D0BWP g1450__2802(.A1 (n_37), .A2 (idata_2[22]), .B1 (n_38), .B2
       (idata_0[22]), .C1 (n_39), .C2 (idata_1[22]), .Z (odata[22]));
  AO222D0BWP g1462__1705(.A1 (n_37), .A2 (idata_2[21]), .B1 (n_38), .B2
       (idata_0[21]), .C1 (n_39), .C2 (idata_1[21]), .Z (odata[21]));
  AO222D0BWP g1458__5122(.A1 (n_39), .A2 (idata_1[20]), .B1 (n_38), .B2
       (idata_0[20]), .C1 (n_37), .C2 (idata_2[20]), .Z (odata[20]));
  AO222D0BWP g1461__8246(.A1 (n_37), .A2 (idata_2[19]), .B1 (n_38), .B2
       (idata_0[19]), .C1 (n_39), .C2 (idata_1[19]), .Z (odata[19]));
  AO222D0BWP g1465__7098(.A1 (n_37), .A2 (idata_2[18]), .B1 (n_38), .B2
       (idata_0[18]), .C1 (n_39), .C2 (idata_1[18]), .Z (odata[18]));
  AO222D0BWP g1468__6131(.A1 (n_37), .A2 (idata_2[17]), .B1 (n_38), .B2
       (idata_0[17]), .C1 (n_39), .C2 (idata_1[17]), .Z (odata[17]));
  AO222D0BWP g1440__1881(.A1 (n_37), .A2 (idata_2[16]), .B1 (n_38), .B2
       (idata_0[16]), .C1 (n_39), .C2 (idata_1[16]), .Z (odata[16]));
  AO222D0BWP g1443__5115(.A1 (n_37), .A2 (idata_2[15]), .B1 (n_38), .B2
       (idata_0[15]), .C1 (n_39), .C2 (idata_1[15]), .Z (odata[15]));
  AO222D0BWP g1463__7482(.A1 (n_39), .A2 (idata_1[5]), .B1 (n_38), .B2
       (idata_0[5]), .C1 (n_37), .C2 (idata_2[5]), .Z (odata[5]));
  AO222D0BWP g1448__4733(.A1 (n_37), .A2 (idata_2[13]), .B1 (n_38), .B2
       (idata_0[13]), .C1 (n_39), .C2 (idata_1[13]), .Z (odata[13]));
  AO222D0BWP g1451__6161(.A1 (n_37), .A2 (idata_2[12]), .B1 (n_38), .B2
       (idata_0[12]), .C1 (n_39), .C2 (idata_1[12]), .Z (odata[12]));
  AO222D0BWP g1452__9315(.A1 (n_37), .A2 (idata_2[11]), .B1 (n_38), .B2
       (idata_0[11]), .C1 (n_39), .C2 (idata_1[11]), .Z (odata[11]));
  AO222D0BWP g1454__9945(.A1 (n_39), .A2 (idata_1[10]), .B1 (n_38), .B2
       (idata_0[10]), .C1 (n_37), .C2 (idata_2[10]), .Z (odata[10]));
  AO222D0BWP g1455__2883(.A1 (n_37), .A2 (idata_2[9]), .B1 (n_38), .B2
       (idata_0[9]), .C1 (n_39), .C2 (idata_1[9]), .Z (odata[9]));
  AO222D0BWP g1459__2346(.A1 (n_37), .A2 (idata_2[8]), .B1 (n_38), .B2
       (idata_0[8]), .C1 (n_39), .C2 (idata_1[8]), .Z (odata[8]));
  AO222D0BWP g1460__1666(.A1 (n_37), .A2 (idata_2[7]), .B1 (n_38), .B2
       (idata_0[7]), .C1 (n_39), .C2 (idata_1[7]), .Z (odata[7]));
  AO222D0BWP g1453__7410(.A1 (n_37), .A2 (idata_2[6]), .B1 (n_38), .B2
       (idata_0[6]), .C1 (n_39), .C2 (idata_1[6]), .Z (odata[6]));
  AO222D0BWP g1447__6417(.A1 (n_39), .A2 (idata_1[14]), .B1 (n_38), .B2
       (idata_0[14]), .C1 (n_37), .C2 (idata_2[14]), .Z (odata[14]));
  AO222D0BWP g1466__5477(.A1 (n_37), .A2 (idata_2[4]), .B1 (n_38), .B2
       (idata_0[4]), .C1 (n_39), .C2 (idata_1[4]), .Z (odata[4]));
  AO222D0BWP g1467__2398(.A1 (n_37), .A2 (idata_2[3]), .B1 (n_38), .B2
       (idata_0[3]), .C1 (n_39), .C2 (idata_1[3]), .Z (odata[3]));
  AO222D0BWP g1469__5107(.A1 (n_37), .A2 (idata_2[2]), .B1 (n_38), .B2
       (idata_0[2]), .C1 (n_39), .C2 (idata_1[2]), .Z (odata[2]));
  AO222D0BWP g1470__6260(.A1 (n_37), .A2 (idata_2[1]), .B1 (n_38), .B2
       (idata_0[1]), .C1 (n_39), .C2 (idata_1[1]), .Z (odata[1]));
  AO222D0BWP g1441__4319(.A1 (n_37), .A2 (idata_2[0]), .B1 (n_38), .B2
       (idata_0[0]), .C1 (n_39), .C2 (idata_1[0]), .Z (odata[0]));
  AO222D0BWP g1442__8428(.A1 (n_37), .A2 (ivalid_2), .B1 (n_38), .B2
       (ivalid_0), .C1 (n_39), .C2 (ivalid_1), .Z (ovalid));
  AO222D0BWP g1444__5526(.A1 (n_37), .A2 (ivch_2[1]), .B1 (n_38), .B2
       (ivch_0[1]), .C1 (n_39), .C2 (ivch_1[1]), .Z (ovch[1]));
  AO222D0BWP g1445__6783(.A1 (n_37), .A2 (ivch_2[0]), .B1 (n_38), .B2
       (ivch_0[0]), .C1 (n_39), .C2 (ivch_1[0]), .Z (ovch[0]));
  AN3D2BWP g1472__3680(.A1 (n_3), .A2 (n_1), .A3 (sel[2]), .Z (n_37));
  AN3D2BWP g1473__1617(.A1 (n_3), .A2 (n_0), .A3 (sel[1]), .Z (n_39));
  CKAN2D2BWP g1471__2802(.A1 (n_2), .A2 (sel[0]), .Z (n_38));
  NR2D0BWP g1474__1705(.A1 (sel[2]), .A2 (sel[1]), .ZN (n_2));
  CKND0BWP g1477(.I (sel[1]), .ZN (n_1));
  CKND0BWP g1475(.I (sel[2]), .ZN (n_0));
  CKND0BWP g1476(.I (sel[0]), .ZN (n_3));
endmodule

