`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Sep  7 2022 16:02:33 CEST (Sep  7 2022 14:02:33 UTC)

module fir_N_Muxb_1_2_11_4(in3, in2, ctrl1, out1);
  input in3, in2, ctrl1;
  output out1;
  wire in3, in2, ctrl1;
  wire out1;
  MX2XL g11(.A (in3), .B (in2), .S0 (ctrl1), .Y (out1));
endmodule



